### ISSUE TITLE
Ensure MassBank.JP statistics are correct

### ISSUE THREAD

**Issue by schymane** [MassBank/MassBank-web#1]
The current massbank.jp statistics page does not seem to include the correct information where records are contributed via massbank.eu, for example the Eawag and UFZ entries in the statistics page (http://www.massbank.jp/en/statistics.html) do not match the numbers on the Record Index (http://www.massbank.jp/RecordIndex.html). We'll calculate the numbers from a mb.eu dump tomorrow and email the maintainers the corrected numbers to update the page manually, but it would be good to get this right automatically

**Comment by tsufz** [comment]
Is the statistics really necessary? This is a lot of handwork and never up to date...

**Comment by schymane** [comment]
I think they are essential, but there must be an automatic way to calculate them. Most of the databases remain static.
If we can't calculate them, who should? It's the best page to get a brief overview - perhaps a revamp may be in order though, to reduce some of the manual labour...
________________________________________

**Comment by tsufz** [comment]
Sure, no problem to derive data from parsed record files. Erik may 
extend the parser to export the updated html file for easy upload to the 
servers.

On 24.11.2015 21:54, schymane wrote:
> I think they are essential, but there must be an automatic way to
> calculate them. Most of the databases remain static.
> If we can't calculate them, who should? It's the best page to get a
> brief overview - perhaps a revamp may be in order though, to reduce some
> of the manual labour...
> ________________________________________
> From: Tobias Schulze [notifications@github.com]
> Sent: Tuesday, 24 November 2015 9:25 PM
> To: MassBank/MassBank-web
> Cc: Schymanski, Emma
> Subject: Re: [MassBank-web] Ensure MassBank.JP statistics are correct (#1)
>
> Is the statistics really necessary? This is a lot of handwork and never
> up to date...
>
> �
> Reply to this email directly or view it on
> GitHub<https://github.com/MassBank/MassBank-web/issues/1#issuecomment-159395432>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MassBank/MassBank-web/issues/1#issuecomment-159402237>.
>

-- 
Dr. Tobias Schulze

Wissenschaftler / Senior Scientist
Department Wirkungsorientierte Analytik / Effect-Directed Analysis

Helmholtz-Zentrum für Umweltforschung GmbH - UFZ
Helmholtz Centre for Environmental Research - UFZ
Permoserstraße 15 / 04318 Leipzig / Germany
phone +49 341 235 1083 / fax +49 341 235 451083
tobias.schulze@ufz.de / www.ufz.de

Sitz der Gesellschaft: Leipzig
Registergericht: Amtsgericht Leipzig, Handelsregister Nr. B 4703
Vorsitzender des Aufsichtsrats: MinDirig Wilfried Kraus
Wissenschaftlicher Geschäftsführer: Prof. Dr. Georg Teutsch
Administrativer Geschäftsführer: Prof. Dr. Heike Graßmann

Bitte denken Sie an die Umwelt bevor Sie diese E-Mail ausdrucken.
Please consider the environment before printing this e-mail.

**Comment by takaakin** [comment]
I am aware of the incorrect statistics.  However, I cannot find the source file of the statistics page. Not too-distant future, I would like to replace to the incorrect one.  Takaaki.

**Comment by schymane** [comment]
Would now be the right time to completely redesign it using Erik's getInfo script? We have all the information in the records, could export two statistics summaries, one for MassBank.jp and one for MassBank.EU. We'd just need to fix the fields we want displayed.
I think this wouldn't be to much work but should be done soon... @ermueller @tsufz
Emma
________________________________________

**Comment by takaakin** [comment]
Dear Emma-san,

 

I would try to use Erik’s getInfo script.  Best regards.

 

Takaaki

**Comment by tsufz** [comment]
> Would now be the right time to completely redesign it using Erik's getInfo script? We have all the information in the records, could export two statistics summaries, one for MassBank.jp and one for MassBank.EU. We'd just need to fix the fields we want displayed.

Is is feasible to write a shell script? Running R in background is an extra step with possible causes of errors (at least a crash).

The shell script may do:
1) Parse the record information to a csv or xml list
2) Do statistics with the parsed record information and create a results csv or xml
3) Create an updated file with the new data for MassBank.jp format
4) For MassBank.eu, I will use a Drupal based frontend in future. We may add a php page which parses the data directly from the statistics csv or xml file?

**Comment by tsufz** [comment]
Needs integration in massbank.jp and maybe some rewriting of R code in order to parse the Japanese statistics page in the correct way (see #16), the R code to run is available here: The relevant changes are in 7dd534e and c8aa707 in my repository.

**Comment by tsufz** [comment]
We can render now a specific low fi statistics page based. Someone may work on the html code generated to tidy up.

**Comment by tsufz** [comment]
Running a statistics script fetching information from the records is implemented. I need to tidy up the html code in order to fit to the general design of MassBank. Then it runs automatically. However, the whole thing needs to deployed on massbank.jp (as a next step after deployment of new massbank.eu?)!

**Comment by tsufz** [comment]
Should be managed with new server software
