### ISSUE TITLE
Validator should not choke on `?` in title

### ISSUE THREAD

**Issue by sneumann** [MassBank/MassBank-web#100]
Some records have question mark in the title.
```
BS003769.txt
';' expected
RECORD_TITLE: 4-Hydroxy-2',4',6'-trimethoxychalcone (Flavokawain A?);
```

**Comment by meier-rene** [comment]
Are you really sure, that question mark should be allowed in chemical names? If yes, I'll add them.

**Comment by schymane** [comment]
It's usually a character import gone wrong and should be curated out; not an issue once we disable the link to mol files, but the name field is how these are linked for now. Title and first CH$NAME should be identical so both would have to be fixed...



On Thu, Dec 7, 2017 at 8:32 AM +0100, "René Meier" <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you really sure, that question mark should be allowed in chemical names? If yes, I'll add them.

**Comment by Treutler** [comment]
Done. '?' is supported in the title.
