### ISSUE TITLE
SP$SAMPLE field description is ambiguous

### ISSUE THREAD

**Issue by meier-rene** [MassBank/MassBank-web#101]
I'm working through record spec file and implementing a validator/data parser atm. I found some Problems in spec file and will ask here questions about problems with spec file and ask for opinions.

In the [summary table](https://github.com/MassBank/MassBank-web/blob/master/Documentation/MassBankRecordFormat.md#table-1--massbank-record-format-summary-not-updated) field SP$SAMPLE is marked as optional and unique field. [Detailed description](https://github.com/MassBank/MassBank-web/blob/master/Documentation/MassBankRecordFormat.md#233-spsample) says "Optional and iterative". No record in MassBank implements "iterative" atm. 

Should i change to unique in detailed description?

**Comment by tsufz** [comment]
I would keep it iterative. A chemical could occur in different species. However, this semantic links are made in other places than MB.

**Comment by meier-rene** [comment]
Fixed code and record spec to removed ambiguity. SP$SAMPLE is now iterative.
