### ISSUE TITLE
Validator does not treat CGH$LINK as iterative

### ISSUE THREAD

**Issue by sneumann** [MassBank/MassBank-web#102]
Hi, the validator chokes on:
```
CH$IUPAC: N/A
CH$LINK: PUBCHEM CID:5280863
CH$LINK: CAS 520-18-3
AC$INSTRUMENT: micrOTOF-Q
```
with 
```
PN000001.txt
AC$INSTRUMENT expected
CH$LINK: CAS 520-18-3
```
-> is it possible that two instances of CH$LINK are confusing the validator ?

**Comment by sneumann** [comment]
That is somewhere near 
https://github.com/MassBank/MassBank-web/blob/master/MassBank-Project/MassBank-lib/src/main/java/massbank/RecordParserDefinition.java#L46

Is it possible that the fields should be defined as `.optional()` `.iterative()` and `optionallyiterative()` ?
Yours, Steffen

**Comment by meier-rene** [comment]
The validator works correct with respect to the record specs. From [CH$LINK](https://github.com/MassBank/MassBank-web/blob/master/Documentation/MassBankRecordFormat.md#228-chlink-subtag--identifier) field:
> CH$LINK fields should be arranged by the alphabetical order of database names.

This means the record should contain:
```
CH$IUPAC: N/A
CH$LINK: CAS 520-18-3
CH$LINK: PUBCHEM CID:5280863
AC$INSTRUMENT: micrOTOF-Q
```

**Comment by sneumann** [comment]
Ah, reading the docs helps. Good, I will also need 
to add that to the converter
