### ISSUE TITLE
Libraryexport for Thermo Software as service

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank-web#103]
By chance, I found out that Thermo enabled the import of MassBank records in mzvault to build a Thermo DB; Michelle, Emma, any experiences with that (Heinz?)? My idea is to provide those libraries with MB spectra together with our future records repository. We can build a single library for each provider and later on merge them to sophisticated collections (e.g. all Orbitrap spectra or all environmental or all MB, etc).

**Comment by takaakin** [comment]
Could you show the URL that describes about the import of MassBank records to mzvault?

**Comment by takaakin** [comment]
Tobias-san,

 

I apologize to all the people of MassBank for my accidentally closing the #103.  

From the next time, I will give a comment without any trouble.

 

Sincerely yours,

Takaaki

**Comment by Treutler** [comment]
Related to #83

**Comment by tsufz** [comment]
We export NIST now, so no further action required from our side so far.
