### ISSUE TITLE
Consider removing requirement of alphabetical ordering

### ISSUE THREAD

**Issue by sneumann** [MassBank/MassBank-web#105]
Hi, currently, the massbank spec document requests sub-tags 
like `CH$LINK` to be in alphabetical order:

https://github.com/MassBank/MassBank-web/blob/master/Documentation/MassBankRecordFormat.md#228-chlink-subtag-identifier

This is not always obeyed by the record writers:
https://github.com/MassBank/RMassBank/issues/188
and I can't see any reason why they must be. 

So the validator should not choke on this, 
and we can also remove it from the specification.
Yours, Steffen

**Comment by meier-rene** [comment]
Validation does not fail on not having alphabetical order any more. So the order is up to the contributor and we have a script which can sort everything in MassBank-data if we want to sort.
