### ISSUE TITLE
Translate existing SOAP services to REST

### ISSUE THREAD

**Issue by Treutler** [MassBank/MassBank-web#106]
... while keeping the SOAP services alive

**Comment by tsufz** [comment]
Highly appreciated :-), we may consider to update the mzMine-to-MassBank interface in parallel. Volunteers?

**Comment by schymane** [comment]
I just had feedback today that someone would like to select the databases searched in the mzMine-MassBank integration (rather than always searching all databases) ... cannot find a relevant issue so posting here...

**Comment by tsufz** [comment]
> I just had feedback today that someone would like to select the databases searched in the mzMine-MassBank integration (rather than always searching all databases) ... cannot find a relevant issue so posting here...

It is already implemented in mzMine. It is possible to select different DBs such as ChemSpider, MassBank.eu, MassBank.jp etc.

**Comment by tsufz** [comment]
See:
https://github.com/mzmine/mzmine2/tree/master/src/main/java/net/sf/mzmine/modules/peaklistmethods/identification/onlinedbsearch/databases

**Comment by schymane** [comment]
I recall similar feedback but thought this was meant differently … rather “would it be possible to search selected sub-databases of MassBank rather than the entire set”? E.g. just Eawag & UFZ & Athens rather than the entire MassBank if you want mainly environmental collections? I.e. can users select the “folders” to search?

**Comment by tsufz** [comment]
Thanks for update. Not yet implemented, I would not touch the mzMine search at this time. We need to implement the new RESTful interface and then update the mzMine part. But we should keep the comment of Emma in mind.

**Comment by naperone** [comment]
see https://jersey.github.io/

**Comment by tsufz** [comment]
I think SOAP is dead an openAPI is alive. Let's close this.
