### ISSUE TITLE
Validator "executable"

### ISSUE THREAD

**Issue by sneumann** [MassBank/MassBank-web#108]
Hi, currently we have instructions to install the validator from source. 
We should have a jar with all dependencies that users only need 
to download and execute locally. Something like https://stackoverflow.com/a/574650
Yours, Steffen

**Comment by schymane** [comment]
Agreed, this would be awesome.

**Comment by sneumann** [comment]
The executable is already built, so no change needed. 
But we have to release it somehow. In the meantime, 
please download from https://msbi.ipb-halle.de/~sneumann/MassBank-lib-0.0.1-SNAPSHOT-jar-with-dependencies.jar
and execute as `java -jar /path/to/MassBank-lib-0.0.1-SNAPSHOT-jar-with-dependencies.jar AAFC/*.txt >/dev/null`

**Comment by meier-rene** [comment]
A package with all executables is now build and created in MassBank-Project/MassBank-lib/target. It can be moved to a different place if needed.
