### ISSUE TITLE
Enhance search capabilities of MassBank

### ISSUE THREAD

**Issue by meier-rene** [MassBank/MassBank-web#111]
It should be useful to add new search capabilities, e.g. to search by InChi key. Might be done by creating a new search option in the quick search page.
![screenshot-2018-5-2 massbank database quick search](https://user-images.githubusercontent.com/25176376/39515732-464c7498-4dfb-11e8-80a8-149df4428ffa.png)

Result page should be similar to recent result page, but maybe with the possibility to directly get the result via deep link. Example:
![screenshot_20180502_112628](https://user-images.githubusercontent.com/25176376/39516515-7127361a-4dfd-11e8-9de8-0363721c2d52.png)

**Comment by schymane** [comment]
Yes ABSOLUTELY we have been waiting for this for ages. See #50, #51, #52 ... 
Direct link with the InChIKey is imho the most important and long overdue, essential for better searching and cross-resource linking... 👍 
Minor points: 
- Please spell InChIKey correctly (second I is also capital).
- Is there a way to fix the "null" values that appear if no chromatography exists (see your screenshots). We should not have a "null" there; this does not appear in previous MassBank versions. 
- I would also vote for changing default Ion Mode setting to "Both" if we can.

**Comment by tsufz** [comment]
Gimme, gimme, gimme, some money :-). `SPLASH` is also important. @naperone And how elastic are we with a full text search now?

**Comment by ChemConnector** [comment]
I think SPLASH has some value but in terms of linking but it is a very small list of sites that would benefit from this IMHO. Rather exposing the InChIKeys and allowing for searching directly, especially via the URL link will enable IMMEDIATE linking from the CompTox Dashboard and other resources such as ChemSpider, PubChem and other database. I think it would drive traffic, provide us (EPA - selfish want) direct linking into Massbank and be of benefit to the solution we are working on to support NTA analysis. 100x votes for InChi over SPLASH

**Comment by tsufz** [comment]
The MB records are fully indexed in the underlying DB now. Hence, the pages are rendered from the DB and not from the records anymore. IMHO, the implementation of each useful identifier should be easy as soon the deployment of the new search function is done. However, we should not overwhelm with identifier search, but implement useful things.

**Comment by meier-rene** [comment]
> The MB records are fully indexed in the underlying DB now. Hence, the pages are rendered from the DB and not from the records anymore. IMHO, the implementation of each useful identifier should be easy as soon the deployment of the new search function is done.
 That is correct and as soon as we have a working implementation for one particular search it is easy to adopt it for every other possible search key as well.

**Comment by naperone** [comment]
c476ec15193bbea7b6bf3c8dd42b6edc86d0a8d9

**Comment by tsufz** [comment]
@naperone: Great, can we also search using a deep link? After review, SPLASH should be also implemented (see #50).

**Comment by meowcat** [comment]
Hi all,

a vaguely related question: are there plans to reintroduce a spectral similarity search, which had to be killed with the Java applet? It's kind of a shame not having that functionality, since it's probably (imo) the most valuable kind of search in a spectral library...

**Comment by tsufz** [comment]
> a vaguely related question: are there plans to reintroduce a spectral similarity search, which had to be killed with the Java applet? It's kind of a shame not having that functionality, since it's probably (imo) the most valuable kind of search in a spectral library...

This issue was dropped so far because the code was not available. I will open a separate issue because this is not related to the quick search functions and should be discussed separately in my opinion.

**Comment by schymane** [comment]
We definitely need to reinstate the proper search function and I agree it’s a separate issue.
However, the quick search functionality offers two chances.

(1)    by allowing retrieval by InChIKey we allow retrieval of all spectra for a given compound so one can assess the best matching spectrum for a given compound (current approach in one of the MetFrag searches).

(2)    There is the possibility to do a SPLASH-related similarity search with the quick search option too, similar to InChIKey first block vs entire key, via the first two or three blocks of the SPLASH. splash10-0g4j (top peaks) and splash10-0g4j-6900000000 (top peaks and histogram) vs splash10-0g4j-6900000000-b43d1386f51d229ee0f4 (exact match).
This shouldn’t replace the option for a user to enter a spectrum and get search results back, but could/should be additional features.

**Comment by naperone** [comment]
@tsufz yes see 72df357ac7f3baf862a083c91d0ffc88b59dcd02.

**Comment by tsufz** [comment]
I fully agree, results page is rather chemical than spectral based. This is also an issue which should be discussed in an own issue.

**Comment by tsufz** [comment]
SPLASH has also problems:

`splash10-0a4i-0000090000-24ab7b106108c494c050` -> no hit
`splash10-0a4i-0000090000`-> 46 hits
`0a4i-0000090000-24ab7b106108c494c050` -> no hit
`24ab7b106108c494c050` -> no hit
`0a4i` -> 2588 hits
`0000090000` -> no hit

Should be one hit (`AC000006 `)

**Comment by Treutler** [comment]
Fixed search for InChIKey-substrings in 732a2fec6e2d5b414d1d456adea835808548a651.
The search for Splash-substrings should work in the dev branch.

**Comment by Treutler** [comment]
Done for now. Please open a new issue if search features are still missing.
