### ISSUE TITLE
Peak search tile is missing on entry page

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank-web#116]
The peak search tile is missing on the entry page. I fixed it on current MassBank.eu, but should be in the sources.

**Comment by sneumann** [comment]
Thanks, can you send the JSP our way or add or attach here ? Thx, Steffen

**Comment by tsufz** [comment]
si, will send pull request soon

**Comment by meier-rene** [comment]
Fixed with da5a93342badfd425b087365a6a782b6336c9e29.
