### ISSUE TITLE
Support RDFa / Bioschema in JSP pages

### ISSUE THREAD

**Issue by sneumann** [MassBank/MassBank-web#119]
Hi, we should support http://bioschemas.org/.

This would require to extend out JSP page https://github.com/MassBank/MassBank-web/blob/088f629074e40ffbfa2ad2d7f9a0f8a3d7fb2d82/MassBank-Project/MassBank/src/main/webapp/jsp/RecordDisplay.jsp#L348

and encode some of the information we display (also) in https://en.wikipedia.org/wiki/RDFa
and https://en.wikipedia.org/wiki/JSON-LD, which would then empower google (and other machine visitors) to extract information.

Some implementation information is in https://docs.google.com/document/d/16ocSdJcQa8XiGZfx9VPam0u1hj3pVglhJPgkijoCZvs/edit#heading=h.2rf1bkfns01y

**Comment by sneumann** [comment]
There is already quite a bit of information in our records, 
as shown in https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fmsbi.ipb-halle.de%2FMassBank%2FRecordDisplay.jsp%3Fid%3DPB002402%26dsn%3DIPB_Halle

**Comment by Treutler** [comment]
see issue #94 
As pointed out I already tried to implement as many tags as possible. Can you point to still missing tags?

**Comment by sneumann** [comment]
Excellent, I had the wrong search term in our issue list to find #94...
