### ISSUE TITLE
MassBank API problems

### ISSUE THREAD

**Issue by Treutler** [MassBank/MassBank-web#121]
I was using the program SoapUI to formulate the request using the address below here is an example of the soap request I am sending and the response, usually for the getInstrumentTypes request the server would return a lift of instruments. I get a response just not the one I expect. 

![massbank_api_01](https://user-images.githubusercontent.com/7373384/41593041-00eccf6c-73bf-11e8-86e6-df05a19c7ebf.png)

![massbank_api_02](https://user-images.githubusercontent.com/7373384/41593054-0ac616c4-73bf-11e8-9880-0e4928e0937d.png)

If I try and retrieve a record I get a response that the record is not found

![massbank_api_03](https://user-images.githubusercontent.com/7373384/41593064-1778306e-73bf-11e8-8050-c398a79d2ed2.png)

I have tried with a variety of different record requests and usually get a response but always at the moment it is returning Record is not found.

**Comment by Treutler** [comment]
@meier-rene and me will have a look a this

**Comment by fgiacomoni** [comment]
@Treutler, do you progress on Massbank API bug. I'm maintaining annotation modules in Workflow4Metabolomics.org (as massbank WS wrapper) and my tools return no results anyway...

**Comment by meier-rene** [comment]
Dear @fgiacomoni,
unfortunately I'm not very familiar with the SOAP technology and I don't know exactly where and how I should start. Are you willing to help us in tracking down the problem? The first thing we need is  way to trace the communication via SOAP. Given the figures you attached in your first post, you already know how to do this. Please get directly in contact with me via meier.rene@ipb-halle.de.

**Comment by fgiacomoni** [comment]
Dear @meier-rene I will try to help you from the soap client side. I will do some tests on Tuesday morning  in case you are behind your computer. Do you have a slack canal?

**Comment by meier-rene** [comment]
just created one: massbankworkspace. I will hang out there tomorrow.

**Comment by fgiacomoni** [comment]
Hi Rene,
I'm starting my tests. Just before go further, may you confirm the WSDL File Address as http://massbank.normandata.eu/MassBank/api/services/MassBankAPI?wsdl for your massbank instance.

**Comment by tsufz** [comment]
Hi Franck, the official url to MassBank.eu is https://massbank.eu/MassBank anyway. The API has no https so far. But I agree with René that the API on massbank.eu may not run.  I plan to upgrade to the new server version in mid of November and thus there is no plan to maintain the old sever except any security updates.

Best wishes
Tobias

**Comment by fgiacomoni** [comment]
Ok thank you for these information and update. I will desactivate temporally my two massbank tools from workflow4metabolomics.org.

**Comment by tsufz** [comment]
I thin SOAP is history now.
