### ISSUE TITLE
dev: Tomcat is not redirected from port 80

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank-web#131]
Tomcat is not yet redirected from port 80 and does not work without Apache. This is maybe useful for implementation: https://support.eapps.com/index.php?/Knowledgebase/Article/View/522/52/tomcat-application-deployment-without-the-apache-web-server#changing-the-apache-port

**Comment by tsufz** [comment]
Actually, what is the rationale to remove Apache? The Apache webroot is containing several files such as the Google Search token and the challenge for the renewal of the Letsencrypt certificate etc. This needs a lot of reconfiguration and reimplementation which I would like to avoid including self-compiling of Tomcat in order to run it non-root (see https://mladenadamovic.wordpress.com/2016/09/06/configure-tomcat-with-ssl-on-ubuntu-minimal). And it needs to be ensured that deployment of a new war does not destroy those services

**Comment by sneumann** [comment]
One can serve static files from tomcat:
https://www.moreofless.co.uk/static-content-web-pages-images-tomcat-outside-war/

**Comment by meier-rene** [comment]
Is think this can be closed, because it can be solved on OS level.
