### ISSUE TITLE
Google dataset search - use markup for page rendering

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank-web#132]
Google started the structured dataset search now. It needs a json set in the page headers.

https://developers.google.com/search/docs/data-types/dataset

https://toolbox.google.com/datasetsearch

We may consider to enhance MassBank with this information?

**Comment by Treutler** [comment]
related to #94 
@meier-rene is currently converting the currently implemented markup to JSON markup. Afterwards we should be datasetsearch-compliant.

**Comment by tsufz** [comment]
@meier-rene, I found one final issue and then we could close this because @egonw confirmed compliance some days ago.

In the database schema is the description tag missing. We have it only in the html header section but not in the json representation.
![image](https://user-images.githubusercontent.com/2526819/81727204-e2d08180-9488-11ea-89ea-d2bd06531c1c.png)

**Comment by egonw** [comment]
@AlasdairGray and I were in an ELIXIR hackathon this week and he commented that on the records it should better be `DataRecord` than `Dataset`, see https://bioschemas.org/profiles/DataRecord/0.2-DRAFT-2019_06_14/ and then the `mainEntity` field can point to the `MolecularEntity` info.

**Comment by tsufz** [comment]
@egonw Was there an progress with with DataRecord draft?

**Comment by AlasdairGray** [comment]
The DataRecord type has ended up causing more challenges than benefits. There is a [proposal](https://github.com/BioSchemas/specifications/issues/475) to remove DataRecord from the set of Bioschemas proposed types.

**Comment by tsufz** [comment]
@AlasdairGray, thanks for the comment. Hence, we go ahead with the 'Dataset' object and additional the 'MolecularEntity'. I enhanced the 'Dataset' object already with the new tag 'measurementTechnique'. So we are ahead of time :-). For example: https://massbank.eu/MassBank/RecordDisplay?id=AU248503. We lack the creator tag, but this needs a rethinking of the MassBank author tag from scratch (see #194).

Best,
Tobias
