### ISSUE TITLE
Representation on ChemSpider

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank-web#148]
Hi,
Is someone in contact with ChemSpider? The present our data using the old links exchanges some while ago:
http://massbank.eu/MassBank/jsp/FwdRecord.jsp?id=EA020103

See:
http://www.chemspider.com/Chemical-Structure.2925.html?rid=86db78b0-b47f-4960-a1d7-9b3fcfe6fa55

What is the plan? Any workaround?

Best
Tobias

**Comment by schymane** [comment]
I am in contact sporadically … I guess they will have to update the links, what should the new links look like? Indeed this one returns a 404:
http://massbank.eu/MassBank/jsp/FwdRecord.jsp?id=EA020103

**Comment by schymane** [comment]
I have contacted them with you two in CC.

**Comment by meier-rene** [comment]
This looks ok now.
