### ISSUE TITLE
Edit/Resubmit query

### ISSUE THREAD

**Issue by dnikol1** [MassBank/MassBank-web#149]
Edit/Resubmit query link does not work. One needs to go back to the main search page if he wants to modify the search terms.

**Comment by tsufz** [comment]
Hi, I transfered this issue, because there was a wrong link on MassBank.

**Comment by meier-rene** [comment]
Thanks @tsufz. Is now working on the public instance. If this version is not working with your way of using MassBank please reopen and describe exactly what you want to achieve and how you want to do it.

**Comment by tsufz** [comment]
If I follow a link in [Record Index ](https://massbank.eu/MassBank/Result.jsp?type=rcdidx&idxtype=site&srchkey=Athens_Univ&sortKey=name&sortAction=1&pageNo=1&exec=), the resubmit does not work properly because it points to RecordIndex.jsp.

**Comment by meier-rene** [comment]
I see. I have to think about how to solve this one...

**Comment by tsufz** [comment]
Hmm. just a simple link back to RecordIndex or is this bundled with the function in the record display?

**Comment by meier-rene** [comment]
Easy fix included in b1aa7a4b1d5ed8772cc84d7c00a852cf8dd013f4.
