### ISSUE TITLE
Add logfile analyzer

### ISSUE THREAD

**Issue by sneumann** [MassBank/MassBank-web#15]
Add a logfile analyzer of the apache logs like awstats or piwik (both are in Ubuntu, piwik preferred,
see http://debian.piwik.org/).
By default, make sure the results are not visible to the outside, but only locally.
Also, enable some privacy protection as mentioned here:
http://piwik.org/docs/privacy/

**Comment by tsufz** [comment]
I like the idea of our webmaster to plug massbank.eu to our central UFZ Piwik appliance. Less implementation and administration efforts and 100% compliance to German data protection regulation.

**Comment by tsufz** [comment]
The massbank.eu server portal will be based on Drupal. Drupal directly supports Piwik and thus I will implement during the massbank.eu relaunch.

**Comment by tsufz** [comment]
Piwik is particularly implement. Needs some final tidy up.

**Comment by tsufz** [comment]
A data privacy page is missing (will include the opt-out button). Will be implemented as soon I checked the piwik installation with our webadmin.

**Comment by tsufz** [comment]
@meier-rene: The default user and password is deployed as the default piwik. Should be considered in implementation of #66. We may also consider to change the salt in config.ini.php
?

**Comment by tsufz** [comment]
More or less implemented. I created a data privacy page with the opt-out. Will be committed as soon my webmaster is back to confirm the piwik deployment and accordance with the text.
