### ISSUE TITLE
Peak Search Results linking error

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank-web#152]
The links in the Peak Search results in the Display.jsp point to the old cgi representation. 
Therefore a peak difference search such as loss of water (18.01056 m/z) is displaying the results, but the records cannot be viewed ([search for water peak loss](https://massbank.eu/MassBank/Result.jsp?op0=and&mz0=18.01056&fom0=H2O&mz1=&fom1=&mz2=&fom2=&mz3=&fom3=&mz4=&fom4=&mz5=&fom5=&int=100&tol=0.3&type=diff&mode=and&op1=and&op2=and&op3=and&op4=and&op5=and&sortKey=name&sortAction=1&pageNo=1&exec=&searchby=mz&searchof=diff&inst_grp=ESI&inst=CE-ESI-TOF&inst=ESI-ITFT&inst=ESI-ITTOF&inst=ESI-QTOF&inst=ESI-TOF&inst=LC-ESI-IT&inst=LC-ESI-ITFT&inst=LC-ESI-ITTOF&inst=LC-ESI-Q&inst=LC-ESI-QFT&inst=LC-ESI-QIT&inst=LC-ESI-QQ&inst=LC-ESI-QTOF&inst=LC-ESI-TOF&ms=MS2&ion=0)).

![2018-12-19 15_25_39-window](https://user-images.githubusercontent.com/2526819/50226043-7724da80-03a2-11e9-99d3-bafecf50eac5.png)

**Comment by Treutler** [comment]
Fixed by 8b14138c8f708a2b1bd432da618791559abc3e5e
