### ISSUE TITLE
Peak Search Results Sorting error

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank-web#153]
Sorting in [Peak Search Results](https://massbank.eu/MassBank/Result.jsp?op0=and&mz0=18.01056&fom0=H2O&mz1=&fom1=&mz2=&fom2=&mz3=&fom3=&mz4=&fom4=&mz5=&fom5=&int=100&tol=0.3&type=peak&mode=and&op1=and&op2=and&op3=and&op4=and&op5=and&sortKey=name&sortAction=1&pageNo=1&exec=&searchby=mz&searchof=peak&inst_grp=ESI&inst=CE-ESI-TOF&inst=ESI-ITFT&inst=ESI-ITTOF&inst=ESI-QTOF&inst=ESI-TOF&inst=LC-ESI-IT&inst=LC-ESI-ITFT&inst=LC-ESI-ITTOF&inst=LC-ESI-Q&inst=LC-ESI-QFT&inst=LC-ESI-QIT&inst=LC-ESI-QQ&inst=LC-ESI-QTOF&inst=LC-ESI-TOF&ms=MS2&ion=0) is faulty.

![2018-12-19 15_53_08-window](https://user-images.githubusercontent.com/2526819/50227699-a9d0d200-03a6-11e9-99f7-ada58cce88d0.png)

**Comment by Treutler** [comment]
fixed with 01aaff558384e6891c74df00fcb5f9080c5ef413
