### ISSUE TITLE
Peak List research - results error

### ISSUE THREAD

**Issue by BBonnefille** [MassBank/MassBank-web#154]
Hi,

I would like to report a bug concerning the" Peak List search" tool since the update of the website.
The results scores are all set at "0.9999" and the results are not corresponding to those given by the previous version of MassBank.
Here is an example of 1/ pick list search results for oxazepam for the previous version of the website (5 top results with a deacreasing score), 2/ same search with the new version (5 top results, no oxazepam proposed in resultats and all scores at 0.9999)

Thank you in advance,
B. Bonnefille

1/ Results for oxazepam MS2 spectra with the previous version of MassBank

![1 oxazepam - old version](https://user-images.githubusercontent.com/46020945/50277871-e273b880-0445-11e9-814a-dba65eadc6e2.png)

2/ Results for (the same) oxazepam MS2 spectra with the new version of MassBank

![2 oxazepam - new version](https://user-images.githubusercontent.com/46020945/50277872-e273b880-0445-11e9-8c52-17c9c549fe2e.png)

**Comment by sneumann** [comment]
Thanks for reporting, we'll try to reproduce and come back to you. 
Yours, Steffen

**Comment by sneumann** [comment]
Thanks for reporting, we'll try to reproduce and come back to you. 
Yours, Steffen

**Comment by sneumann** [comment]
Hi, can you provide us with an exact query to reproduce this ? 
I used the Example1 with all defaults, and got different result scores. yours, Steffen

**Comment by BBonnefille** [comment]
Hi Steffen,
Thank you for your reply.
I do not have access to my data until January 8. I will send you the data used to reproduce the request as soon as possible.
Yours, Bénilde Bonnefille

**Comment by BBonnefille** [comment]
Hi Steffen,
As discussed, you will find attached the data entered for the query for which I obtained the above results. The search was carried out using the default parameters for an analysis in positive ionization mode with an ESI source (all MS levels). The data are presented as pairs m/z / intensity ratio without any pre-selection of the experimental data.
Yours, Bénilde 
[MS2_oxazepam.txt](https://github.com/MassBank/MassBank-web/files/2735890/MS2_oxazepam.txt)

**Comment by schymane** [comment]
@meier-rene or @Treutler or @sneumann  or others - any progress here? 
We have just received emails to check progress; an update would be great. Thanks!

**Comment by meier-rene** [comment]
Hi, I think we could fix this problem and its online available on our development server https://msbi.ipb-halle.de/MassBank/ . Could you please test there and report your findings?

**Comment by BBonnefille** [comment]
Hi,
First, thank you four the feedback.
I just did the requested test, and it seems much better! (see search results below)
However, the results are different from those obtained with the previous version: the highest score is not the same as on the results initially obtained (first example in the first message of this discussion), and the best "match" does not correspond to the same MassBank spectrum although the research data are identical. Unless these spectra have been removed from MassBank, there may still be a problem there?

Concerning the 'Instrument type': the results does not show any problem of instrument type selection, I only get results in ESI, as requested (for the first 20 results).

![image](https://user-images.githubusercontent.com/46020945/51664617-1f3d4d00-1fba-11e9-8d9f-0ac8b7701d0e.png)

**Comment by BBonnefille** [comment]
I wrote too quickly: I confirm the 'Instrument type' selection problem. I requested only (LC-)ESI-QTOF results (always with the oxazepam data) and obtained all the ESI Instrument type results.

**Comment by meier-rene** [comment]
We have deployed a new code base on our test system. [Please try!](https://msbi.ipb-halle.de/MassBank) We are quite confident, that the results of the similarity score and the number of hits are now equal within the accuracy of the algorithm compared to the old version. Nevertheless you will find some minor differences in the floating point numbers, but that's not very unusual after a refactoring of code, a change of java version, different operating system and different hardware. Floating point operation have always a limited accuracy. 
Nevertheless there is a difference in number of matched peaks for your example (fig. below) which we can not explain. I'm wondering how you could obtain a hit count of 86 for the second hit in the old Massbank if the query spectra has only 82 peaks. There is something strange with this numbers. 82 is definitely the max with your attached spectra. Maybe the old MassBank was giving incorrect values for this field...
![screenshot_2019-02-01 massbank database quick search results](https://user-images.githubusercontent.com/25176376/52120621-277e3380-261d-11e9-9174-51650b3ddbef.png)
)

**Comment by schymane** [comment]
Thank you very much for your efforts @meier-rene 
Look forward to hearing the feedback from @BBonnefille to see if this indeed resolves the issues they experienced

**Comment by BBonnefille** [comment]
Hi, I performed the test as requested and I get results in agreement with those obtained before the update of MassBank (I get the same results that the ones you attached).
Thank you for all the work you have done to correct the issues we have encountered.
I hadn't noticed the problem of the number of hits that seems to be solved with the corrected version you propose. Perhaps this problem was due to the difference in the acquisition mode of the reference spectrum data versus the submitted data (low resolution in opposition to high resolution).
Thank you again,
Bénilde

**Comment by Treutler** [comment]
Issue seems to be solved. @BBonnefille thank you for testing. Update will be life on the public server in the next rollout..

**Comment by BBonnefille** [comment]
Hi,
I come back to you to obtain more information about your previous message (dated February 4): do you know when the next MassBank public server rollout will be completed?
Thank you in advance.
Bénilde

**Comment by meier-rene** [comment]
We want prepare a fix for #156 before we do the next public rollout. Please use https://msbi.ipb-halle.de/MassBank/ until this has completed.
