### ISSUE TITLE
Result structure and order broken.

### ISSUE THREAD

**Issue by meier-rene** [MassBank/MassBank-web#156]
@schymane  wrote: I'm seeing very strange things with MassBank searching ... (records appearing many, many times; no default settings making it look like we have nothing in the library etc etc)

Look how many times we have (the same) records of nicotine, they repeat every second entry for a while ... same for benzotriazole

https://massbank.eu/MassBank/Result.jsp?compound=Nicotine&op1=and&mz=&tol=0.3&op2=and&formula=&type=quick&searchType=keyword&sortKey=not&sortAction=1&pageNo=1&exec=&inst_grp=ESI&inst=CE-ESI-TOF&inst=ESI-ITFT&inst=ESI-ITTOF&inst=ESI-QTOF&inst=ESI-TOF&inst=LC-ESI-IT&inst=LC-ESI-ITFT&inst=LC-ESI-ITTOF&inst=LC-ESI-Q&inst=LC-ESI-QFT&inst=LC-ESI-QIT&inst=LC-ESI-QQ&inst=LC-ESI-QTOF&inst=LC-ESI-TOF&inst_grp=Others&inst=APCI-ITFT&inst=APCI-ITTOF&inst=CI-B&inst=FAB-B&inst=FAB-BE&inst=FAB-EB&inst=FAB-EBEB&inst=FD-B&inst=FI-B&inst=LC-APCI-ITFT&inst=LC-APCI-Q&inst=LC-APCI-QTOF&inst=LC-APPI-QQ&inst=MALDI-QIT&inst=MALDI-TOF&inst=MALDI-TOFTOF&ms=MS2&ion=0

Summary:
-number of spectra incorrect
-same spectra appear multiple times
-ordering is broken

**Comment by meier-rene** [comment]
just referencing discussion at a different place #issuecomment-463546679.

**Comment by sneumann** [comment]
Hi, I need some explanation here. In the search above, 
we have two records KO003603 and KO003605 that only differ in the CID eV. 
Why are they not grouped ? They have the same `CH$NAME` entries.
Yours, Steffen

**Comment by schymane** [comment]
That is the point … something is broken (badly).
See screenshot – if you expand the selection, then 11 spectra reported, but only 1 displayed? 6 spectra but only one displayed?
36 hits but way more than 36 displayed (because of repetition)

[cid:image001.png@01D4C45A.3D21E800]

**Comment by schymane** [comment]
![image](https://user-images.githubusercontent.com/4070141/52781720-901dd500-304d-11e9-875f-75f6798e9a35.png)

**Comment by Treutler** [comment]
Partially fixed with f8ee6a14ddb19f7d4e4e5db164ac2630adb032c7
@meier-rene will add defaults for instrument type / MS type / Ion Mode

**Comment by meier-rene** [comment]
Defaults for new user are added now and completely empty search requests get caught before the search is submitted. Search results are already fixed for a while. As soon as we have a new rollout its also available for the public. Preview is available at https://msbi.ipb-halle.de/MassBank/
