### ISSUE TITLE
Result Table sorting by name is case sensitive

### ISSUE THREAD

**Issue by sneumann** [MassBank/MassBank-web#160]
Hi, if I go to 
https://msbi.ipb-halle.de/MassBank/Result.jsp?type=rcdidx&idxtype=site&srchkey=UFZ&sortKey=name&sortAction=1&pageNo=1&exec=
and then sort by name, the sorting is case sensitive (hint: sort descending), then you see 
```
p-Toluenesulfonamide 
o-Toluidine 
o-Dianisidine 
Warfarin 
Verapamil 
...
```
Would users expect `o` and `O` to be nearby ? Yours, Steffen

**Comment by Treutler** [comment]
Fixed in a1c2a4d345d0fb287f3e30c326dc00fea441ef36
