### ISSUE TITLE
Spectrum search

### ISSUE THREAD

**Issue by dnikol1** [MassBank/MassBank-web#164]
Would it be possible to allow more than one space between m/z and intensity? For some reason copy spectrum list/ paste from MassLynx always make more than one space resulting in Invalid format error message. Kind of annoying to manual remove spaces...

**Comment by schymane** [comment]
We should be able to deal with tabs too, ie any form of whitespace ...

**Comment by meier-rene** [comment]
Fixed with 2e70e49c246816ebab15adedb5c18a937a109e98. All combinations of whitespaces and tabs are now supported. You can try on our https://msbi.ipb-halle.de/MassBank/.
