### ISSUE TITLE
Remove link to user manual from all pages

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank-web#165]
the user manual is somewhat outdated. I suggest to remove it and all links at all.

**Comment by schymane** [comment]
As long as there is a new manual to replace it? I'd rather update than remove?

**Comment by tsufz** [comment]
This manual is not usable and confuses the users. It is hardly related to old theme of massbank.jp. Of course, we need to write a new manual, could be done with the about pages.

**Comment by tsufz** [comment]
se #163
