### ISSUE TITLE
MassBank records can't be found

### ISSUE THREAD

**Issue by schymane** [MassBank/MassBank-web#167]
I can't find any records by record accession any more, even if they are 100 % for sure in MassBank-data

https://massbank.eu/MassBank/NoRecordPage?id=EA030311&error=Error:%20Can%20not%20find%20contributor
![image](https://user-images.githubusercontent.com/4070141/55462900-2c00a180-55f8-11e9-93b3-b520e8458dd1.png)

![image](https://user-images.githubusercontent.com/4070141/55462931-3e7adb00-55f8-11e9-9df1-b251d3e32c14.png)

https://github.com/MassBank/MassBank-data/blob/master/Literature_Specs/LIT00020.txt#L1

**Comment by meier-rene** [comment]
@tsufz If I remember correctly, there is an automatic record update process running. Could you please check if there are any issues with this process. The requested records are just not in the database and I'm wondering why.

**Comment by tsufz** [comment]
Update is running every 6 hours, should be enough at normal conditions. An update is running in the moment...
