### ISSUE TITLE
Broken google links to records

### ISSUE THREAD

**Issue by Treutler** [MassBank/MassBank-web#168]
Searching in google for 'MassBank rutin' results in the broken link (404)
https://massbank.eu/MassBank/jsp/RecordDisplay.jsp?id=PR020080&dsn=
which should be
https://massbank.eu/MassBank/RecordDisplay.jsp?id=PR020080&dsn=
or
https://massbank.eu/MassBank/RecordDisplay.jsp?id=PR020080

We should think about a solution for this.

**Comment by meier-rene** [comment]
Haw can google find this pages if they are not static?

**Comment by tsufz** [comment]
Hüstel, there is no record representation on Google by now, just old broken links.... For any reason, the bot stops at the recordindex. I need urgently to fix the automated sitemap shell. Something to plug behind automated data update script.

**Comment by sneumann** [comment]
Is that script in the massbank-web repo ? If not Tobias would be the only person on the planet to fix. 
One can also add a redirect from .../jsp/... to just .../ , making sure it returns code "301 Moved Permanently"
in the meantime.

**Comment by meier-rene** [comment]
I propose to create a dynamic sitemap.xml from the current online MassBank via a servlet. I will prepare that.

**Comment by tsufz** [comment]
We have the existing [Sitemap.sh](https://github.com/MassBank/MassBank-web/blob/master/MassBank-Project/MassBank/src/main/webapp/script/Sitemap.sh). The sitemap should also contain the main pages such as Index, Search, RecordIndex, Data Privavy, Imprint, depending on pages listet in the menu.jsp / html.

**Comment by meier-rene** [comment]
I have created an automatic sitemap servlet and designed some rewrite rules for apache which redirect the old jsp/Dispatcher.jsp URL to the new RecordDisplay.jsp: 

#***************************************************
# For MassBank
#***************************************************

RewriteEngine on
RewriteRule ^/MassBank$ /MassBank/ [R]
RewriteCond %{REQUEST_URI} ^/MassBank/jsp/Dispatcher\.jsp$
RewriteCond %{QUERY_STRING} ^type=disp&(id=[0-9A-Z]+).*$
RewriteRule (.*) /MassBank/RecordDisplay.jsp?%1 [R=301,L,QSD]
RewriteRule ^/MassBank/(.*) http://your_massbank_ip:8080/MassBank/$1 [L,P]
