### ISSUE TITLE
Search issues still: full query returns 186,591 records 

### ISSUE THREAD

**Issue by schymane** [MassBank/MassBank-web#174]
... but our record index says we have approx 56,000 only ...

E.g.:
https://massbank.eu/MassBank/Result.jsp?inchikey=&type=inchikey&searchType=inchikey&sortKey=not&sortAction=1&pageNo=1&exec=&inst_grp=EI&inst=EI-B&inst=EI-EBEB&inst=GC-EI-Q&inst=GC-EI-QQ&inst=GC-EI-TOF&inst_grp=ESI&inst=CE-ESI-TOF&inst=ESI-ITFT&inst=ESI-ITTOF&inst=ESI-QTOF&inst=ESI-TOF&inst=LC-ESI-IT&inst=LC-ESI-ITFT&inst=LC-ESI-ITTOF&inst=LC-ESI-Q&inst=LC-ESI-QFT&inst=LC-ESI-QIT&inst=LC-ESI-QQ&inst=LC-ESI-QTOF&inst=LC-ESI-TOF&inst_grp=Others&inst=APCI-ITFT&inst=APCI-ITTOF&inst=CI-B&inst=FAB-B&inst=FAB-BE&inst=FAB-EB&inst=FAB-EBEB&inst=FD-B&inst=FI-B&inst=LC-APCI-ITFT&inst=LC-APCI-Q&inst=LC-APCI-QTOF&inst=LC-APPI-QQ&inst=MALDI-QIT&inst=MALDI-TOF&inst=MALDI-TOFTOF&ms=all&ms=MS&ms=MS2&ms=MS3&ms=MS4&ion=0

![image](https://user-images.githubusercontent.com/4070141/56743516-feca8d80-6776-11e9-946f-be66238eb32a.png)

c/o wikidata debugging, thanks @egonw 

![image](https://user-images.githubusercontent.com/4070141/56743586-1efa4c80-6777-11e9-8b51-8f74c7aa7b4b.png)

And here's what our record index says:

![image](https://user-images.githubusercontent.com/4070141/56743608-2e799580-6777-11e9-8057-2d24d8b25d4b.png)

Adding ion type gives me 56263 ...

**Comment by sneumann** [comment]
confirmed on msbi.ipb-halle.de The ion_type will be the crucial hint to Hendrik ;-)

**Comment by Treutler** [comment]
Fixed in 4ef599b75d940861d1d781e09eff7c26887dfcff
The default behavior in case of an empty InChIKey string is to return all records matching the remaining criteria (also done this way in the Keyword search).
