### ISSUE TITLE
Display issues in some fields?

### ISSUE THREAD

**Issue by schymane** [MassBank/MassBank-web#177]
Some strangeness in the display of some fields seems to have crept in very recently, first I've noticed it, e.g. for title, authors, date, comments and instrument type?

![image](https://user-images.githubusercontent.com/4070141/57830777-79edf500-77b3-11e9-9020-4b2d704e1cf0.png)

![image](https://user-images.githubusercontent.com/4070141/57830791-83775d00-77b3-11e9-9765-8434a9d3a5e7.png)

![image](https://user-images.githubusercontent.com/4070141/57830802-8a9e6b00-77b3-11e9-9eae-d97e1832e37c.png)

Any idea why? Can this be fixed quickly? Looks very strange...

**Comment by Treutler** [comment]
This issue seems to depend on `span` tags, which are used to get semantic information into the record page. We observed this one day in the past, but the problem went away the next day on its own...
However, the issue will be obsolet when we switch to the new record display (in the next rollout?).

**Comment by schymane** [comment]
I still see these issues ... :-(

**Comment by tsufz** [comment]
No release update yet...

**Comment by tsufz** [comment]
... rolled out to MB server...

**Comment by schymane** [comment]
I still see issues, even for spectra I've not looked at on this browser before?
![image](https://user-images.githubusercontent.com/4070141/58014529-5d2a2800-7af9-11e9-8219-2c4c65f0a68c.png)

**Comment by tsufz** [comment]
The new display scheme is not rolled out yet and thus those spoky impressions do persist...

**Comment by meier-rene** [comment]
This is fixed now.
