### ISSUE TITLE
Version and data of MassBank record format

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank-web#179]
The version and date is not very up to data. Can we automatise it?

**Comment by meier-rene** [comment]
Maybe... Could you please be more specific what information you want to have at what place?

**Comment by schymane** [comment]
Well ... aren't we still version 2?
We could consider having a 2.X.Y system ... so all minor and relatively major changes could be communicated. Timestamping to get a "last modified date" should be relatively easy?

**Comment by schymane** [comment]
(but yes I agree we need more info from @tsufz what he is envisaging)

**Comment by tsufz** [comment]
I have no specific opinion on the numbering, but it must be updated (as well as the date) if we update the content. However, a 2.x.x system might be good. But at least the last change date should be covered, best automatically.

**Comment by tsufz** [comment]
Solved in eb46e80724dfab645a8e1be1495a9b7048a743b8
