### ISSUE TITLE
Update of databases using the SVN system?

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank-web#18]
Test if the update of existing DBs is possible using the SVN system. Needs test system with running SVN and internal SVN mirroring system.

**Comment by takaakin** [comment]
Over a couple of weeks, MassBank.jp server did not properly work. We replaced to new memory boads yesterday.  I would like to watch the server few days whether it runs with no any other troubles before the test you request.  I am not familiar with the SVN system.  So what can I do for the test?  Takaaki

**Comment by tsufz** [comment]
merged into #29
