### ISSUE TITLE
"Keyword" search

### ISSUE THREAD

**Issue by schymane** [MassBank/MassBank-web#182]
I don't find the name of the "Keyword" tab particularly intuitive to guess that this is the tab where you can search name, formula or mass. Is there perhaps an alternative we could use? A mass is not really a keyword, nor is a formula - maybe "Basic" or "Compound Info"?

![image](https://user-images.githubusercontent.com/4070141/60274628-ac355b00-98f8-11e9-84ad-3d9db9d27d24.png)

**Comment by meier-rene** [comment]
This sounds reasonable and I have changed it to "Basic Search"
