### ISSUE TITLE
HTTP Status 404 after call of multidisplay on results page

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank-web#196]
I got a report by Stephen Stein from NIST. If I call the example 1 in peak list search, the multidisplay results in error 404.

HTTP Status 404 – Not Found

Type Status Report

Message /MassBank/Display.jsp

Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.
Apache Tomcat/8.5.45

**Comment by sneumann** [comment]
Seems that there are two leftover-buttons from old MassBank times. 
Quick fix: remove them. Mid-term fix: Get Functionality back.
Yours, Steffen

**Comment by tsufz** [comment]
Yes, I think so....

**Comment by tsufz** [comment]
Fixed on massbank.eu. However, the tick boxes should also be removed...

**Comment by tsufz** [comment]
The lines are find in QpeakResults.jsp line 383-388.
