### ISSUE TITLE
Documentation is missing file encoding

### ISSUE THREAD

**Issue by laeubi** [MassBank/MassBank-web#208]
The [documentation](https://github.com/MassBank/MassBank-web/blob/master/Documentation/MassBankRecordFormat.md) is missing one important information: What is the expected encoding of the file? I would assume UTF-8 but can't find a reference.

**Comment by tsufz** [comment]
The old manual was removed because it is outdated. A new one will be created as soon as possible.

**Comment by schymane** [comment]
Is it sensible to completely remove documentation in the absence of an updated version? Out of date may be better than nothing?
