### ISSUE TITLE
Develop a Markdown User Manual

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank-web#227]
Hi, I suggest to remove the outdated PDF user manual.

Yours,
Tobias

**Comment by sneumann** [comment]
We could consider converting to markdown plus updating, 
nothing wrong having documentation. Also related to #165 
Yours, Steffen

**Comment by tsufz** [comment]
Oh yes, we should have a manual, indeed also a PDF one.

**Comment by meier-rene** [comment]
A markdown [manual](https://github.com/MassBank/MassBank-documentation) is now in place. Its also accessible from MassBank site with the Documentation buttons. The MassBank-documentation repo also includes the "News" page. All chenges to news and manual will automatically appear on MassBank without rollout.

**Comment by schymane** [comment]
Awesome!
Just ... https://github.com/MassBank/MassBank-documentation/blob/master/user_documentation.md looks a bit empty. Is this intended (as in, is it still to come)?

**Comment by meier-rene** [comment]
Unfortunately this is the case.
