### ISSUE TITLE
Record format issue

### ISSUE THREAD

**Issue by sneumann** [MassBank/MassBank-web#235]
Hi, we got a report about an inconsistency 
``` 
an error in the MassBank Record Format 2.5.
[Error] 2.5.1 Subtag: PRECURSOR_MZ
[Correct] 2.5.1 Subtag: PRECURSOR_M/Z

"/" is missing in the current format.
``` 

The `PRECURSOR_M/Z` was indeed present in the `MassBankRecordFormat_en.pdf` files 
up to at least 2017, and also still in https://github.com/MassBank/MassBank-web/blob/9c1ff657782ced8cc830bd3da0a5a39a018f5821/Documentation/MassBankRecordFormat.md#251-subtag-precursor_mz

Yours, Steffen

**Comment by schymane** [comment]
I guess we decided to avoid the `/` if possible, but didn't update validation properly?
What is the current format in MassBank-data records?

**Comment by sneumann** [comment]
Hunting the change down, it was still `M/Z` in 2018:
https://github.com/MassBank/MassBank-web/blob/b0236c387938c0aa582dcc20c429de63e846f688/Documentation/MassBankRecordFormat.md#251-subtag-precursor_mz

**Comment by sneumann** [comment]
The change was part of this commit https://github.com/MassBank/MassBank-web/commit/6208e9a01560c28223cf981d45fd20216bd33fcb

The `PRECURSOR_M/Z` was mentioned in this issue https://github.com/MassBank/MassBank-web/issues/96 before, and deemed valid. 

Can @tsufz and @meier-rene comment whether we had a discussion preceding the change to `PRECURSOR_MZ` ? 
Yours, Steffen

**Comment by tsufz** [comment]
Yes, there was a short discussion in https://github.com/MassBank/MassBank-web/issues/200#issuecomment-546857625. @meowcat asked to avoid slashes w/o complains. Thus, I removed the slashes.

**Comment by tsufz** [comment]
In https://github.com/MassBank/MassBank-web/issues/200#issuecomment-546866390, I asked for comments on the proposal of the records format. I have no problems with the slashes, but the all tags should be the same.

**Comment by tsufz** [comment]
There are related open issues to update the records to be compliant with the new record format if appropriate:

- https://github.com/MassBank/MassBank-data/issues/99
- https://github.com/MassBank/MassBank-data/issues/98

Hence, no record is changed so far. Happy to discuss all issues and the updated record format.

Best,
Tobias

**Comment by sneumann** [comment]
I would expect a lot of code out there in the world uses the `PRECURSOR_M/Z` of the existing records, 
and I would be strongly against mass-changing the records. Instead I would like 
to see our documentation adapted/reverted to the old state. Yours, Steffen

**Comment by schymane** [comment]
Agree with @sneumann ...

**Comment by tsufz** [comment]
I have no problems to adapt the old stage. However, could you check the other suggestions, please. I am also no friend of mass changes of records. But in my opinion it is necessary have consistent tags. See https://github.com/MassBank/MassBank-data/issues/99  and https://github.com/MassBank/MassBank-data/issues/98.

**Comment by meier-rene** [comment]
I checked all records. We dont have any records with *_MZ tags. All records have *_M/Z. There are two tags: MASS_RANGE_M/Z and PRECURSOR_M/Z. I dont care about / in tag names and to prevent mass change of records without any benefit I will revert format spec to to _M/Z.

**Comment by schymane** [comment]
Sounds good to me @meier-rene 
Can you pls check MassBank? it's looking ill ...

**Comment by meier-rene** [comment]
Yes, we know, but dont know the reason.

**Comment by schymane** [comment]
OK, glad you know and are on to it ... good luck & let me know if you need assistance in any way ...

**Comment by meier-rene** [comment]
Done with 7447c2f502ad70af5122885971b31f7d049cdcd9.
