### ISSUE TITLE
Move MassBank EU to cloud computing service

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank-web#24]
Moving MB EU from UFZ would make administration easier as for example Steffen could also access the server for administration issues. I suggest to use for example EGI: https://www.egi.eu/services/cloud-compute/

I recently talked to Jaroslav, he generally agrees. EGI is maybe less expensive than  any private provider. And we would upgrade MB EU to real European level using the European Community cloud services.

**Comment by schymane** [comment]
Sounds like a plausible option – worth considering. Have you looked into any other options?

**Comment by tsufz** [comment]
An alternative would be EUDAT. I like the option to deploy own VM's with 
own resources management (easy commitment of more power, storage etc.) 
with EGI. This makes us independent from any institutional constrains, 
but also more responsible for proper server maintenance.

**Comment by tsufz** [comment]
We talked about this topic yesterday during the IPB / UFZ hackathon. We may postpone for some time until major changes in MB are finalised.

**Comment by tsufz** [comment]
No plans so far. Close in meanwhile.
