### ISSUE TITLE
Numeric issues for intensities in MassBank-web

### ISSUE THREAD

**Issue by sneumann** [MassBank/MassBank-web#242]
Hi, we got a report that our abundances look strange:

https://msbi.ipb-halle.de/MassBank/RecordDisplay?id=PB006042
```
PK$PEAK: m/z int. rel.int.
  115.053 5775.77978515625 576.0
  116.057 640.6409912109375 63.0
```
MassBank-data https://github.com/MassBank/MassBank-data/blob/master/IPB_Halle/PB006042.txt has 
```
PK$PEAK: m/z int. rel.int.
  115.053 5775.776 576
  116.057 640.641 63
```
The OpenAPI has the same values: https://msbi.ipb-halle.de/MassBank-OpenAPI/record/PB006042
@meier-rene has already an idea. Yours, Steffen

**Comment by meier-rene** [comment]
This is fixed now and the Validator also tests numerical issues like this in the future. Thanks for reporting.
