### ISSUE TITLE
Quality assessment, metadata enrichment and curation of old and new records

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank-web#25]
Curation tool for the assessment of quality of MB records should be available. Could be based on RMassBank (annotation of peaks based on the peak list?). This should include a quality tag in the records to give users more confidence. This is related to #12, which could be also merged into this tool.

**Comment by tsufz** [comment]
Suggestion of #12 
I suggest a better enrichment of the meta tags of each record site to improvement indexing by the crawlers, for example the InChIkey and SPLASH could be added here. Needs enhancement of the DB model to map more content from the records.

**Comment by tsufz** [comment]
Curation suite should also upgrade version 1 records to version 2 records in order to consolidate.

**Comment by tsufz** [comment]
Erik and I suggest to enhance the RMassBank Uni test for this purpose (https://github.com/MassBank/RMassBank/blob/master/R/validateMassBank.R)

**Comment by tsufz** [comment]
Hi, I would like to start the discussion of curation again. As discussed today in issue #81, a curation and subsequent infiltration of curated data into the existing record files is an important issue to improve reliability of MassBank data. I see no problems to touch all records under any CC-BY license as modifications are allowed. We curate the existing meta tags and not MS data. And we did with injection of the SPLASH anyway. Hence, can we agree on the implementation of (auto-)curation methods starting with the name tag manipulation? All changes will be visible in the new SVN systems and hence transparent (with the opportunity to revert to an older version). Autocuration means that, most stuff should be done in an automated way, but any change needs approval by a curator in order to avoid further missmatches.

**Comment by schymane** [comment]
I think we should discuss, but I would like to hold off doing anything until we have done a partial update with what @ChemConnector and I have been doing, which I will answer in #81

**Comment by Treutler** [comment]
All records have been updated to Version 2.
The syntax of all records is validated.
Records have been curated with e.g. SPLASH and structure identifier (InChI/SMILES/InChIKey).
The semantics of records still needs some work.
If there are open points here, please open a new issue in MassBank-data: https://github.com/MassBank/MassBank-data
