### ISSUE TITLE
Changes to Syntax for Metabolomics USIs

### ISSUE THREAD

**Issue by meier-rene** [MassBank/MassBank-web#250]
We got this information:
Letting you all know, Wout and I had a few conversations with the
Proteomics USI team about identifiers that would conform in style to
proteomics spectral libraries. There are basically 3 changes that
we'd need to do that would simply require in most cases an
few characters on your side. These are basically made to support
versioning of spectra if that were the case (though likely we
wouldn't have it on the GNPS side but would be consistent with
Proteomics libraries). 

These are the changes that would happen for libraries

1. The first block becomes mzdraft for ones that have not
specifically been verified by the PSI USI folks
2. The third block would denote some version, but could be left blank
3. The fourth block denotes the type of value for the
identifier (fifth block)

mzspec:MASSBANK:SM858102 -> mzdraft:MASSBANK::accession:SM858102
mzspec:MOTIFDB:motif:171163 -> mzdraft:MOTIFDB::accession:171163

For our own analysis tasks

1. The first block becomes mzdraft for ones that have not
specifically been verified by the PSI USI folks
2. Second block determines the resource
3. The third block is a dataset accession
4. The fourth block denotes the type of value for the
identifier (fifth block)

mzspec:MS2LDATASK-38:document:43062 -> mzdraft:MS2LDA:TASK-
190:accession:43062
mzspec:GNPSTASK-
c95481f0c53d42e78a61bf899e9f9adb:spectra/specs_ms.mgf:scan:1943 ->
mzdraft:GNPS:TASK-c95481f0c53d42e78a61bf899e9f9adb-
spectra/specs_ms.mgf:scan:1943

Wout and I have already updated the metabolomics USI website to
handle these new styles, but have not merged/deployed. 

What we need from you:

1. Simon -> Update links for MS2LDA/MOTIFDB to the new USI style
2. Rene/Tobias -> Update Massbank links to the new USI style
3. Ming -> Update linkouts on GNPS Libraries/Tasks to the new USI
style

Once we have all these in place along, we will switch everything over
on the resolution side to make sure we have minimal downtime. 

I was hoping we'd aim for 2 weeks from now to make the change. Let me
know if that works for you all!

**Comment by schymane** [comment]
... this is all fair enough and understandable (and hopefully achievable?), semantically I am not a fan of `mzdraft` and would be keen to know what we could do to earn the `mzspec` upgrade from PSI ASAP ... does anyone know how to do this?

**Comment by meier-rene** [comment]
Done
