### ISSUE TITLE
Suggested minor updates to news

### ISSUE THREAD

**Issue by schymane** [MassBank/MassBank-web#267]
I've tried to find the file to update but come up empty handed ... 

Minor typo to be fixed (two hs): 
```
 Links

MassBank community on Githhub
```

...and I would suggest to add the Metabolomics Spectrum Resolver to the Links or News collection (currently in the archive)

![image](https://user-images.githubusercontent.com/4070141/97785700-f7bfdf00-1ba6-11eb-9661-30356c84f304.png)

Thanks!

**Comment by sneumann** [comment]
Hi Emma, the stuff is sitting in a separate repo, 
so that we can use github pages for that repo, and embed the pages 
into the MassBank web application. The typo is in:
https://github.com/MassBank/MassBank-documentation/search?q=githhub
Typo is corrected, the MSIR still a todo.  Yours, Steffen

**Comment by schymane** [comment]
Great, thanks!

**Comment by tsufz** [comment]
Added to links in latest news update.

**Comment by tsufz** [comment]
Btw. The MSIR is already implemented.

**Comment by schymane** [comment]
Yes I know it's already implemented (the news item in the archive says this) but I think it's a useful thing to keep in the links section so that people can find it also from this landing page ... not just the records.

**Comment by tsufz** [comment]
@schymane, this was related to the comment of @sneumann.
