### ISSUE TITLE
Exact mass display has far too many decimal places...

### ISSUE THREAD

**Issue by schymane** [MassBank/MassBank-web#269]
Hi all,

It seems the exact mass display has gone a little crazy ... can we please truncate at a sensible number (e.g. the number of decimal places in the record ... or 4 d.p. ... but please not display like this?). Thanks!

![image](https://user-images.githubusercontent.com/4070141/99290620-d31e6500-283e-11eb-990a-b43bfb411213.png)

![image](https://user-images.githubusercontent.com/4070141/99290675-e3cedb00-283e-11eb-98d3-adf1f15398dd.png)

![image](https://user-images.githubusercontent.com/4070141/99290785-1082f280-283f-11eb-9d20-d879b871b669.png)

https://github.com/MassBank/MassBank-data/blob/main/Eawag/EA000401.txt#L13

![image](https://user-images.githubusercontent.com/4070141/99290835-242e5900-283f-11eb-9b7a-63860518be3b.png)

**Comment by sneumann** [comment]
Hi, I'd say fixed in the code, see
https://msbi.ipb-halle.de/MassBank/RecordDisplay?id=EA000401
but not yet rolled out on MassBank.eu
Yours, Steffen

**Comment by tsufz** [comment]
Hmm, as soon a committ makes its way to massbank.eu branch, the new server will be deployed. The preferred way is to push manually, could be also automated as I check the new deployed instance before going productive anyway.

Best,
Tobias

**Comment by meier-rene** [comment]
I will take a look into it and report back.

**Comment by meier-rene** [comment]
I can not reproduce this issue. @tsufz have you already changed the codebase on massbank.eu? Its reporting 2.1.6 which is the latest release.

**Comment by tsufz** [comment]
I agree with @tsufz. Do you run your private MB server @schymane? Which is maybe not updated?

**Comment by tsufz** [comment]
Äh I agree with @meier-rene

**Comment by tsufz** [comment]
massbank.eu is fine:
![image](https://user-images.githubusercontent.com/2526819/99513771-433a0180-298b-11eb-8736-4c820b2a48a3.png)

but massbank.jp is not:
![image](https://user-images.githubusercontent.com/2526819/99513903-6cf32880-298b-11eb-9238-8d3e9c3ee2ca.png)

**Comment by tsufz** [comment]
Code base of massbank.jp is 2.1.4

**Comment by schymane** [comment]
Cannot reproduce any more either ... the best issue ever, fixed itself magically ;-)

**Comment by tsufz** [comment]
healing hand magics....
