### ISSUE TITLE
Consider adding "About" and "News Archive page"

### ISSUE THREAD

**Issue by sneumann** [MassBank/MassBank-web#273]
Hi,

I would be happy about an "About" page (pun was initially NOT intended!) with normal sized logos plus 1-2 sentences about the partners, and make the logos in the footer small enough to still fit on one line as it is now. 

While at it, I'd support a separate page for the news archive, the front page is getting a bit long. 

=> Should we have "About" + "News Archive" in the https://github.com/MassBank/MassBank-documentation ? 

Yours, 
Steffen

**Comment by schymane** [comment]
Sounds like a great idea to me!

**Comment by schymane** [comment]
Do you want content suggestions in the issue, or would you prefer to set up skeletons for us to fill?

**Comment by tsufz** [comment]
Good morning,
I fully agree. The homepage is overloaded with all the information anyway. At all, I would prefer an embedded solution (including the documentation). I don't like this pop up window. We load the pages dynamically from GitHub anyway, but the website structure should be visible and it should be easy to move to the other pages again. I think it is also a legal issue. We have to provide the imprint also for the documentation.

Best,
Tobi

**Comment by tsufz** [comment]
ah, and I would add the about to the menu and not to the documentation. The About is more static anyway.

**Comment by meier-rene** [comment]
Done in dev branch.
