### ISSUE TITLE
Close old SVN architecture

### ISSUE THREAD

**Issue by sneumann** [MassBank/MassBank-web#29]
Currently, the SVN is used to synchronize between JP and EU.
Data from JP is inserted into SVN, and EU does an `svn update`
and locally inserts them into massbank.eu

The refactoring should create a standalone SVN server, and *all* 
MassBanks commit to this SVN. 

* Use /mbadmin to upload a ZIP and place that into SVN
* Use /mbadmin to import (part of) the SVN into the MassBank system
* Allow these operations also from command line tools (see #28 ).

**Comment by tsufz** [comment]
SVN seems not to run in the current stage. The SVN classes are available, but the deployment is not implemented (no servlets in the web.xml).
As a workaround, I created local DBs for each contributor and uploaded all records rescued from the old MassBank.eu server. Quite annoying task for the rollback...

**Comment by meier-rene** [comment]
I added the servlet to web.xml, but it doesn't work. There is a problem with the decryption of the password. I don't know how to fix it, because I don't know how the backend works.

**Comment by tsufz** [comment]
Dispose old SVN architecure

**Comment by Treutler** [comment]
done. moved to MassBank-data on GitHub: https://github.com/MassBank/MassBank-data
