### ISSUE TITLE
[RecordFormat] Harmonizing Annotation

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank-web#299]
The very customized tagging of annotation is rather confusing for people using downstream workflows. We should review the format of annotation and make it more straightforward. For example, the annotations should be in one format and we just add a tag if they are tentative, manual, automated etc.

**Comment by schymane** [comment]
Can you please clarify what you mean by annotation? (what exact field(s) in MassBank records are you referring to?)

`annotation` can be used in several contexts ...

**Comment by stanstrup** [comment]
I think Tobias is referring to #301 that I brought up in the hackathon.

**Comment by tsufz** [comment]
Yes.
