### ISSUE TITLE
Highlighting "how to contribute" a bit more?

### ISSUE THREAD

**Issue by schymane** [MassBank/MassBank-web#311]
Just a flag for now ... but going to the MassBank website, it's not particularly obvious that you can contribute spectra, or how. We may wish to consider making this more prominent somehow?

**Comment by meier-rene** [comment]
Thats a good point. I will try to make a highlighted link to our contributor documentation on the landing page for our next release.

**Comment by schymane** [comment]
Thanks, sounds like a good plan!

**Comment by meier-rene** [comment]
What about this? You think this is ok?

![screenshot-localhost_8080-2021 09 13-09_05_58](https://user-images.githubusercontent.com/25176376/133038886-d92735d0-f9b2-411f-9ddf-adb05a788edd.png)

**Comment by schymane** [comment]
Yes @meier-rene this looks good ... I was wondering if the top of the News was the best location too ;-)
