### ISSUE TITLE
Create private vagrant bootstrap settings

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank-web#35]
Some bootstrap settings are maybe confidential (e.g. passwords). Should be moved to a private bootstrap script which is listed in .gitignore to prevent the upload to a public repository

**Comment by tsufz** [comment]
This issue is related to #66. The rest can be done with private branches. I can write a short notice in the readme. Close with #66.

**Comment by Treutler** [comment]
closed with #66
