### ISSUE TITLE
Split download in main categories to improve user experience

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank-web#350]
@schymane, I just added this issue to the list:

> Yes, I found the latest release on [Github](https://github.com/MassBank/MassBank-data/releases/tag/2021.12) and [Zenodo](https://zenodo.org/record/4563726#.YnQN7tpBxPY) , I meant I cannot find them split by instrument (GC / LC) or ionization (ESI+, ESI-, EI).
> I would say these main categories would be good to allow to download them separately

**Comment by tsufz** [comment]
Yes, I would agree for the `msp` and `sql` dumps, but not for the `txt` files. A person working with `txt` could easily separate them tailored, IMHO.

**Comment by meier-rene** [comment]
This issue is shifted to the MassBank3 REST API and the respective front end.
