### ISSUE TITLE
docker compose v2

### ISSUE THREAD

**Issue by meowcat** [MassBank/MassBank-web#364]
The install.sh script uses `docker-compose`. 
With the advent of "docker compose v2", `docker-compose` ceases to be a standalone executable, and `docker compose` is used instead. It should work more or less drop-in. 

https://docs.docker.com/compose/compose-v2/
https://github.com/docker/compose

On Debian, `apt-get install docker-compose` still installs docker-compose "v1", but this is probably not desired; some recommend to just alias `docker-compose` to `docker compose`.

I find the communication regarding deprecation of "old" docker-compose a bit lacking, nevertheless we should probably implement it?

**Comment by meier-rene** [comment]
Thank you for the heads-up. I wasn't aware of this. Of course we will follow this transition. If its as easy as a simple drop-in I will adjust the documentation, or if some tweaks are required add them.

**Comment by meier-rene** [comment]
Fixed in dev.
