### ISSUE TITLE
Command line switch for Inspector to emit only the JSON+LD 

### ISSUE THREAD

**Issue by sneumann** [MassBank/MassBank-web#365]
Hi, 
currently `MassBank-lib/bin/Inspector` returns an entire HTML page including the embedded JSON+LD.
I'd love to see a switch `--only-jsonld` that only exports the actual JSON+LD without any HTML around it. 
That'll help with #357 .
Yours,
Steffen

**Comment by meier-rene** [comment]
Added in [8adfb07](https://github.com/MassBank/MassBank-web/commit/8adfb07b941343fa87d0a8c1310b336fcd98b142).
