### ISSUE TITLE
Error in Record List Generator in mbadmin tools

### ISSUE THREAD

**Issue by Treutler** [MassBank/MassBank-web#37]
Just start new Massbank (empty except one record) using Vagrant (vagrant up) and go to mbadmin tools (http://192.168.xx.xx/MassBank/mbadmin/)
Go to Record List Generator (http://192.168.xx.xx/MassBank/mbadmin/GenRecordList.jsp)
Select Database Massbank and click Execute.

message An exception occurred processing JSP page /mbadmin/GenRecordList.jsp at line 158
description The server encountered an internal error that prevented it from fulfilling this request.
exception

org.apache.jasper.JasperException: An exception occurred processing JSP page /mbadmin/GenRecordList.jsp at line 158

155: 				short col2 = (short)(item.length - 1 + n);
156: 				HSSFCell cell = hsRow.createCell(col2);
157: 				int pos = idList[n].indexOf(" NAME=");
158: 				String id = idList[n].substring( 0, pos );
159: 				String recordName = idList[n].substring( pos + 6 );
160: 				
161: 				cell.setCellValue(new HSSFRichTextString(id));

Stacktrace:
	org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:568)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:470)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:727)

root cause

java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	java.lang.String.substring(String.java:1911)
	org.apache.jsp.mbadmin.GenRecordList_jsp._jspService(GenRecordList_jsp.java:243)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:727)

note The full stack trace of the root cause is available in the Apache Tomcat/7.0.52 (Ubuntu) logs.

**Comment by tsufz** [comment]
I have no problems. Maybe a problem of access control?

**Comment by Treutler** [comment]
fixed by commit 5e1855362dcba2fa6887c844e5db0ec028a08d41
