### ISSUE TITLE
Validator.java page not found

### ISSUE THREAD

**Issue by animesh** [MassBank/MassBank-web#375]
![image](https://user-images.githubusercontent.com/21457/221848200-d60a6183-37b7-464d-b186-198e3c305940.png)

**Comment by meier-rene** [comment]
Hi, we need more information to deal with your report. In my browser everything looks ok.

**Comment by animesh** [comment]
Thanks @tsufz , i actually reached it via https://github.com/MassBank/MassBank-data where they link up https://github.com/MassBank/MassBank-web/blob/main/MassBank-Project/MassBank-lib/src/main/java/massbank/Validator.java , will ask them to change it to https://github.com/MassBank/MassBank-web/blob/main/MassBank-Project/MassBank-lib/src/main/java/massbank/cli/Validator.java 👍🏽
