### ISSUE TITLE
incomplete regexp

### ISSUE THREAD

**Issue by egonw** [MassBank/MassBank-web#377]
The current regular expression is `^MSBNK-[A-Z0-9_]{1,32}-[A-Z0-9_]{1,64}$` ([source](https://github.com/MassBank/MassBank-web/blob/main/Documentation/MassBankRecordFormat.md#211-accession)) but this does not match `MSBNK-Fac_Eng_Univ_Tokyo-JP001576` which has a hyphen in the second block.

I propose updating the regexp to `^MSBNK-[A-Z0-9_]{1,32}-[A-Z0-9_-]{1,64}$`, adding the hyphen as allowed in the second block.

**Comment by schymane** [comment]
The hyphen divides the blocks, with three in total ... it looks like it matches to me?

**^MSBNK**-[A-Z0-9_]{1,32}-**[A-Z0-9_]{1,64}$**

and

**MSBNK**-Fac_Eng_Univ_Tokyo-**JP001576**

...with bold indicating first and third blocks respectively? The char count seems OK in the second block ...

**Comment by egonw** [comment]
Right. Sorry. I made the wrong conclusion indeed. The problem is the regexp fail in Wikidata: https://www.wikidata.org/wiki/Wikidata:Database_reports/Constraint_violations/P6689#%22Format%22_violations

**Comment by meier-rene** [comment]
But we have a mistake in the regex in our documantation at a different place.
`echo MSBNK-Fac_Eng_Univ_Tokyo-JP001576 | grep -E "^MSBNK-[A-Za-z0-9_]{1,32}-[A-Z0-9_]{1,64}$" `

So regex should be `"^MSBNK-[A-Za-z0-9_]{1,32}-[A-Z0-9_]{1,64}$" ` and not `"^MSBNK-[A-Z0-9_]{1,32}-[A-Z0-9_]{1,64}$"` . I will fix that. Thanks for reporting.
