### ISSUE TITLE
Improvement and consilidation of html page headers

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank-web#39]
Taging is not consistent over the different scripts and we may consider better enrichment of

**Comment by tsufz** [comment]
See:
https://developers.google.com/search/docs/guides/intro-structured-data
https://developers.google.com/search/docs/guides/search-features

Google may also introduce datasets:
https://developers.google.com/search/docs/data-types/datasets

**Comment by Treutler** [comment]
I am not entirely sure about this issue.
@tsufz can you please point me to an example where taging is not consistent or could be improved?

**Comment by tsufz** [comment]
Your site has no hreflang tags.
Google uses hreflang tags to match the user's language preference to the right variation of your pages.

**Comment by tsufz** [comment]
Google also provides a dataset content types in it's structured data policy. Hence, we could provide some Json snippets in which we parse information?

**Comment by tsufz** [comment]
https://developers.google.com/search/docs/data-types/dataset

**Comment by tsufz** [comment]
An improvement of the keywords tag could be useful. The keywords are quite non narrative:
<meta name="keywords" content="1H-Benzotriazole, mass spectrum, MassBank record, mass spectrometry, mass spectral library">

I suggest to parse at least:

- Accession
- InChIKey
- Truncate "MassBank record" to "MassBank"

However, the description tag is missing at all. It was considered as more useful than the keywords tag. See https://www.lifewire.com/keywords-in-html-3469351.

**Comment by tsufz** [comment]
This was implemented at some point.
