### ISSUE TITLE
Deprecate version control in install.sh?

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank-web#390]
`sh ./install.sh start x` results in

```
./install.sh: 22: [[: not found
Docker compouns V2 not found, Expected 2.x.
```

Docker compose version 2.20.2

**Comment by meier-rene** [comment]
Shell 'sh' is not compatible with the  "if [[ $OUT = 2* ]]" syntax. Please use "bash ./install.sh start x" or make install.sh executable if it isn't already just use "./install.sh start x".

**Comment by tsufz** [comment]
Okay, Thanks!
