### ISSUE TITLE
Docker compose version is not estimated correctly in `install.sh`

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank-web#395]
```
$ bash ./install.sh start 2`
Docker Compose V2 version 2.20.2 found. Using command 'docker compose'.
```

```
$ docker-compose -v
docker-compose version 1.xx
```

docker compose has version 1.xx, so the query is not working correctly.

**Comment by meier-rene** [comment]
You are right. I already realized this issue and I tried to fix it in dev. I will make some more testing and if everything is fine I will hotfix this in the release.

**Comment by tsufz** [comment]
Okay, was maybe a local problem due to some fixes of the local install.sh, but I wait for your tests before I release new server.

**Comment by meowcat** [comment]
Docker compose v1 (`docker-compose`) may be present *in addition to* Docker compose v2 (`docker compose`). So I don't think this is necessarily a bug.

**Comment by meier-rene** [comment]
All is good now I think. I have made some small modifications two weeks ago and tested all combinations I'm aware of. Tobias also resolved his issue. This can be closed.
