### ISSUE TITLE
Improve developer friendlieness

### ISSUE THREAD

**Issue by sneumann** [MassBank/MassBank-web#40]
Hi, the current massbank-web is a conglomerate of files extracted from the former 
binary installer and the old CVS version control system. @meier-rene has already 
started work (at https://github.com/meier-rene/MassBank-eclipse) to import all 
relevant files into an Eclipse project. Even developers with different IDEs will benefit 
from the cleaner structure. This issue can be closed once that file structure is imported.
Yours, Steffen

**Comment by Treutler** [comment]
Massbank-web is now in a eclipse-compatible format and can hence be easier developed
