### ISSUE TITLE
MS5 and "merged MSn" spectra

### ISSUE THREAD

**Issue by meowcat** [MassBank/MassBank-web#403]
Hi,

I am working with a contributor who collected a ton of MSn spectra. Two things:
* they have MS5 spectra, which are not currently in RecordParserDefinition.java. Can we add MS5 to the definition?
* they also have "merged MSn" spectra, where all MSn spectra have been pooled to a single spectrum. I would suggest to simply add "MSn" as a definition for those. Would you agree? Or do we want to avoid these?

**Comment by schymane** [comment]
I can't help with point (1) but agree that it should be added. Regarding point (2), I think these spectra should be included (not avoided), either as "MSn" or "merged MSn"?

**Comment by meowcat** [comment]
For the FOCUSED_ION we could either
`PRECURSOR_M/Z 581.18649/merged`
or just like you suggest
`PRECURSOR_M/Z 581.18649`

The slashes exist anyway in MSn records so the field is already not numeric. (Same, actually, for the collision energies, both for MSn and for all the stepped/merged MS2.) From that point of view, "merged" would not cause much more damage... One could argue that it's not extra information if the record says "MSn merged" anyway. I guess your suggestion is better.

The suggestion for DATA_PROCESSING would currently be 
`MS$DATA_PROCESSING: SPECTYPE ALL_MSN_TO_PSEUDO_MS2`

**Comment by meier-rene** [comment]
This is included in release 2.2.6.
