### ISSUE TITLE
Commons HttpClient is eol

### ISSUE THREAD

**Issue by meier-rene** [MassBank/MassBank-web#49]
Massbank uses Commons HttpClient internally for communication with Apache httpd. Commons HttpClient is eol since 2011 and should be replaced by Apache HttpComponents Client.

**Comment by tsufz** [comment]
Tomcat complains: 
WARN  org.apache.commons.httpclient.HttpMethodBase - Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.

Is this related to this issue?

**Comment by tsufz** [comment]
@Treutler Can we close with 3d996ee9aad8c16957f373e06ea792fe6a99861f

**Comment by meier-rene** [comment]
Exactly, 3d996ee closes this issue.
