### ISSUE TITLE
Link to record(s) via SPLASH

### ISSUE THREAD

**Issue by sneumann** [MassBank/MassBank-web#50]
Hi, it would be great to link to records via a SPLASH, 
e.g. https://massbank.eu/splash/splash10-000i-3900000000-73043667076aaf483c6e

**Comment by tsufz** [comment]
see my comments in #51

**Comment by Treutler** [comment]
Done. Implemented deeplink via e.g. http://localhost:8080/MassBank/Result.jsp?splash=splash10-000i-3900000000-73043667076aaf483c6e
