### ISSUE TITLE
Link to record(s) via InChIkey

### ISSUE THREAD

**Issue by sneumann** [MassBank/MassBank-web#51]
Hi, it would be great to link to records via an InChIkey,
e.g. https://massbank.eu/inchikey/RYYVLZVUVIJVGH-UHFFFAOYSA-N

**Comment by tsufz** [comment]
To implement we need the following steps:
1) Enhancement of the DB model including indexing of all record content (#9)
2) Upgrade of all records to version 2 and curation of old records (#25)
3) Implementation of new code for search options (#52)

Hence, It's lot of work which cannot be done within days... Marc and me are working on the implementation of MoNA. I have a docker available, but my priority is to setup the new MB.eu.

**Comment by schymane** [comment]
What is the time frame for getting this done? Is this something that will be achievable soon, without necessarily going through step 2 (upgrade of all records to version 2 and curation)?

**Comment by tsufz** [comment]
There is no time frame so far. We will have a developer meeting next week and then we will discuss the topics. I guess all records are version 2, are there any records without InChIkey?

**Comment by schymane** [comment]
I am not sure if the entire MassBank is version 2?
There are version 2 records without InChIKeys, as in, substances with an InChIKey field but the InChIKey is not defined. There are also some records without InChIKeys I think, AAFC maybe. We will probably have to cover all cases? Take a look in the record summary for to get an overview of the "outliers"
________________________________________

**Comment by schymane** [comment]
We really need to prioritize this, at ACS we received quite a few comments asking why MassBank (EU) is not interlinked with the Dashboard (and other resources). It would be awesome if we could implement soon to push the cross-linking forward...

**Comment by ChemConnector** [comment]
I think the number of requests that I have personally heard for in-linking
now is over a dozen. Then add on the requests made directly after my
presentation at ACS then we have to imagine how many requests we are not
hearing. I agree. HIGH priority.

Tony Williams

Phone: +1 (919) 201-1516
Email: tony27587@gmail.com
Skype: tony27587
My Blog: www.chemconnector.com
Twitter: http://twitter.com/ChemConnector

**Comment by Treutler** [comment]
Done. Implemented deeplink via e.g. http://localhost:8080/MassBank/Result.jsp?inchikey=RYYVLZVUVIJVGH-UHFFFAOYSA-N
InChIKey still needs curation for some records and will be done shortly.
