### ISSUE TITLE
Rendering by Specktackle is strange

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank-web#54]
Mail from @schymane
Re the depiction, the structures that are currently on MassBank.EU look strange, with the atoms but no Hs. Is this adjustable?
http://massbank.eu/MassBank/jsp/Dispatcher.jsp?type=disp&id=ETS00115&site=32&dsn=Eawag_Addn
e.g. the CH3 group should not be missing the H3, and I would prefer that Cs are suppressed automatically, it just looks strange.
http://massbank.eu/MassBank/jsp/Dispatcher.jsp?type=disp&id=ETS00019&site=32&dsn=Eawag_Addn
Ditto here, the OHs are missing the Hs, this is NOT a standard representation...and the chain looks weird with a stepped C-C-C-C-C...

**Comment by tsufz** [comment]
This is only a problem if the mols are not rendered to GIFs, the Gifs show the Hs, have a look. I hope on the new server, the rendering is running correctly again and thus this a minor issue.

**Comment by Treutler** [comment]
Is this issue closed with the works in #47?

**Comment by schymane** [comment]
I think this is long solved with the move to CDK? Closing ...
