### ISSUE TITLE
Implement CDK links

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank-web#55]

**Comment by schymane** [comment]
CH$LINK: CDK_DEPICT_SMILES 
CH$LINK: CDK_GENERIC_SMILES 
CH$LINK: CDK_SUBSTRUCTURE_SMILES
@tsufz already has 2 examples, @schymane to do more

**Comment by tsufz** [comment]
Needs URL encoding of the smiles by the dispatcher. The dispatcher cannot handle the entries in the recors without wrapping. @naperone can program the wrapper?

The entries in the Disp.cgi are:

'CH\$LINK: CDK_DEPICT_SMILES',			'https://cdkdepict-openchem.rhcloud.com/depict/cow/svg?smi=%s&abbr=off&suppressh=true&showtitle=false&zoom=1.3&annotate=none',
'CH\$LINK: CDK_GENERIC_SMILES',			'https://cdkdepict-openchem.rhcloud.com/depict/bow/svg?smi=%s&abbr=off&suppressh=true&showtitle=false&zoom=1.3&annotate=none',
'CH\$LINK: CDK_SUBSTRUCTURE_SMILES',	'https://cdkdepict-openchem.rhcloud.com/depict/cow/svg?smi=%s&abbr=off&suppressh=true&showtitle=false&zoom=1.3&annotate=none',

**Comment by tsufz** [comment]
I guess, this issue can be closed with #47? We may need to change the tagging a little bit if a single CDK tag works, but we don't need dispatching any more.

**Comment by tsufz** [comment]
Close with #9.

**Comment by sneumann** [comment]
CDKdepict moved to http://www.simolecule.com/cdkdepict/depict.html

**Comment by Treutler** [comment]
Done. Implemented for
CH$CDK_DEPICT_SMILES
CH$CDK_DEPICT_GENERIC_SMILES
CH$CDK_DEPICT_STRUCTURE_SMILES
