### ISSUE TITLE
Typo "fasle".

### ISSUE THREAD

**Issue by sneumann** [MassBank/MassBank-web#6]
There is a typo in the display of the RecordList:
````
find . -type f | xargs grep fasle
./Tomcat/webapps/ROOT/MassBank/mbadmin/RecordList.jsp:	    {"CH_LINK", "fasle"},
./modules/tomcat/webapps/MassBank/mbadmin/RecordList.jsp:	    {"CH_LINK", "fasle"},
````
in https://github.com/MassBank/MassBank-web/blob/81d0039a1af66c031db3cc1dadeea828c4eecf09/Tomcat/webapps/ROOT/MassBank/mbadmin/RecordList.jsp#L86 and https://github.com/MassBank/MassBank-web/blob/81d0039a1af66c031db3cc1dadeea828c4eecf09/modules/tomcat/webapps/MassBank/mbadmin/RecordList.jsp#L84

When fixing, check that this has no unintended side effects.

**Comment by takaakin** [comment]
I corrected the error on MassBank.jp server.   Thanks.  Takaaki

**Comment by tsufz** [comment]
dito on massbank.eu, I don't see side effects. nevertheless this is an internal tool and thus no external display.
