### ISSUE TITLE
Record format update

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank-web#61]
New CH$LINK tags need to be implemented.

**Comment by schymane** [comment]
Addressed with [d3086ba](https://github.com/MassBank/MassBank-web/commit/d3086bab976049536c463bc75aae8d2a1399857a)

**Comment by schymane** [comment]
Reopening this, needs to be updated again to reflect the CDK changes? @tsufz

**Comment by tsufz** [comment]
Updating the record format is running task and doesn't need own task in my opinion.
