### ISSUE TITLE
Results.jsp: Remove buttons to obsolete applets

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank-web#64]
The results page shown by URL http://massbank.eu/MassBank/jsp/Result.jsp?type=quick includes buttons to execute obsolete applets.

**Comment by Treutler** [comment]
Removed the buttons 'Multiple Display' and 'Spectrum Search' on results.jsp page in commit 7eca8261e338b5543b13b997961c4d0a104a2553.
