### ISSUE TITLE
Replace generic user bird and default password by customised user and password

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank-web#66]
I think it is a security issue to run MassBank with the public passwords. We should consider to include a routine which replaces the default by customised ones.

**Comment by Treutler** [comment]
we configured the docker container for local access only in commit 49af36113841d06ddd5c2913801a79c9accf22e6
just delete your old docker container with:

`docker stop massbankweb_mariadb_1`
`docker rm massbankweb_mariadb_1`

and start it again with

`docker-compose up -d`

security issue still there, but it is not accessible any more from outside

**Comment by tsufz** [comment]
okay, great!

**Comment by meier-rene** [comment]
The provisioning of the vagrant container requires the user now to set a USERNAME and PASSWORD. They are used to secure the mbadmin area for now and will hopefully also be used on the databases in the future. But this requires substantially more work.

**Comment by tsufz** [comment]
Yes, nice, but does not work on Windows. I will write a batch file to handle the command.

**Comment by tsufz** [comment]
USERNAME is a system variable in windows and cannot be used in this context. It stores the currently logged in user.

**Comment by tsufz** [comment]
and USER is the logged in user in UNIX.... so another change...

**Comment by tsufz** [comment]
Sorry, This is not working on Windows. I suggest to revert to the setting before the hacks.

**Comment by meier-rene** [comment]
I just tried it on Windows and it works for me. `MBUSERNAME=massbankuser PASSWORD=massbankpassword vagrant up` is bash syntax and will not work on windows.  Honestly, I never expected that someone runs this on Windows. Instead of the above mentioned command please try this on windows `cmd`:
```
set MBUSERNAME=massbank
set PASSWORD=mypassword
vagrant up
```
Hope this helps. Please try it one more time. Of course if it worksdocs need to be updated as well ...

**Comment by tsufz** [comment]
I added a batch file to start the installation. I had a typo btw.

**Comment by meier-rene** [comment]
Great, I suppose it is working then on Windows as well. Now I will figure out a mechanism to propagate this user/password information through the whole system to remove generic user once and for all from Massbank.

**Comment by tsufz** [comment]
Yes, works on Windows now. Another philosophical question: Would it not better to separate the backend to have a "secret" mysql user+pw and a frontend password user+pw for the administration tool? In issue #23  we will implement https, but in few cases the people may  use unsecured access shouting out the sectret...

**Comment by meier-rene** [comment]
I will prepare usage of user/password combinations for database and backend separately. Every server admin can decide if he wants to use separate passwords or not, although separate passwords are more advanced and might require some manual adjustments. But they will be technically independent. Just for ease of use they are the same atm.

**Comment by Treutler** [comment]
done. Now fully configurable. See massbank.conf
