### ISSUE TITLE
Dispose CGI files

### ISSUE THREAD

**Issue by Treutler** [MassBank/MassBank-web#67]
We should perform database requests and the remaining functionality in *.cgi files in Java to streamline the MassBank project.
This would make the Apache server obsolete and dispose an old technology and another programming language from the project. Especially database requests can be done much more securely in java.

**Comment by tsufz** [comment]
Sounds good to me! But if we roll up the code, we may consider to replace the existing DB model in parallel (see #9)?

**Comment by Treutler** [comment]
done.
