### ISSUE TITLE
Missing TLD in some JARs

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank-web#68]
From /var/log/tomcat8/catalina.out
INFO: Deploying web application archive /var/lib/tomcat8/webapps/MassBank.war
Jul 05, 2017 10:21:41 AM org.apache.jasper.servlet.TldScanner scanJars
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Jul 05, 2017 10:21:41 AM massbank.MassBankEnv envListLog
INFO: MassBank environment variable list.

DEBUG gives no more information

**Comment by Treutler** [comment]
We are not sure what to do here. Please give us a hint here.
