### ISSUE TITLE
Deployment of new MassBank.war destroys existing structure on MassBank

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank-web#73]
The deployment of a newly compiled MassBank.war destroys the existing DB structure. Afterwards only the default database is visible. I guess, the installer deploys the default sql and overwrites the basic mariadb?

I suggest to build an upgrade script which:
1) backups the existing /var/lib/tomcat8/webapps/MassBank and /var/www/html/MassBank folders
2) dumps the mariadb into a sql dump
3) compiles and deploys the new MassBank.war
4) deploys the old DB structure

If the deployment is not working properly, a rollback script to the old server version should be available

**Comment by tsufz** [comment]
Another option would be that the webapp grabs the existing massbank.conf, creates new databases from here and uploads the existing records in DB/annotation. In this case we deploy possible new DB structures and changed pathways without annoying new creation of DBs and nasty upload of recdata.

**Comment by Treutler** [comment]
I do not see how the deployment of a newly compiled MassBank.war could destroy the existing DB structure. I can not reproduice this.

I do not know the details of the deployment, but is it possible that
`/var/www/html/MassBank/massbank.conf`
(which records the information about the present databases) is overwridden by 
`modules/apache/html/MassBank/massbank.conf`
from the war?

You could check
`http://l[host]/MassBank/massbank.conf`
whether the databases are still recorded there and if yes you could check whether the databases are still present (`mysql -u bird -h [host] -p` and in mysql `SHOW DATABASES;`).

**Comment by tsufz** [comment]
I checked the recent version with my test server, no problems either. There was maybe any temporal problem. txs so far.. Close #73.
