### ISSUE TITLE
CH$LINKs are missformated

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank-web#74]
After commit 024ac4a24582ad13660edf536568160ff62a91e0, the CH$LINK field are interpreted strangely. This hinders the Disp.cgi to dispatch the outlinks correctly, here for example (SM870902):

CH$LINK: 926-72-7 CAS
CH$LINK: CID:8859 PUBCHEM
CH$LINK: SQSPRWMERUQXNE-UHFFFAOYSA-N INCHIKEY
CH$LINK: 8527 CHEMSPIDER

Should be:
CH$LINK: CAS 926-72-7
CH$LINK: PUBCHEM CID:8859
CH$LINK: INCHIKEY SQSPRWMERUQXNE-UHFFFAOYSA-N
CH$LINK: CHEMSPIDER 8527

I dunno how this can happen, maybe a changed variable?

**Comment by Treutler** [comment]
My fault! Fixed with commit 4f96bf3cae088c376d20688f19a6dea343c4b48f
By the way: disp.cgi is not used anymore and RecordDisplay.jsp does the job instead.
