### ISSUE TITLE
Remove strange / deprecated stuff from mbadmin

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank-web#75]
SQL File Generator; some strange artefact and only valid for records format 1
File Upload; I prefer upload using the command line via ssh or sftp
Structure registration; not needed anymore due to SVG rendering from records #47 
Structure list; should be replaced by a viewer as suggested in #47 
Validator; see SQL File Generator
Version information; I have no real opinion. Checkup against GIT? We never change version number; for it is deprecated

**Comment by Treutler** [comment]
Removed structure registration and structure list from mbadmin in commit a7b27cdddd69db82ae6d3fa595ff9fd407d2e475.

**Comment by Treutler** [comment]
Do we need the SqlFileGenerator and the Validator (then we updateit) or can we remove this?

**Comment by tsufz** [comment]
I dunno what is the SqlFileGenerator good for; I think nobody needs this when we will have a good API.

The validator is for format 1 spectra only. I would remove it here, but I suggest a general validation tool available on the homepage (I will open new issue).

**Comment by tsufz** [comment]
I would also remove the Record List generator. It it buggy and we should think about the possibility to download a csv with all record information (particularly implemented in the statistics page generation; the intermediate statistics.csv can be downloaded). However, with #9 we could implement a better presentation of the statistic page and provide a comprehensive csv for download for those not so familiar with API or html stuff.

**Comment by Treutler** [comment]
removed mbadmin completely.
