### ISSUE TITLE
Performance of httpclient

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank-web#76]
WARN  org.apache.commons.httpclient.HttpMethodBase - Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.

It's in /var/log/tomcat8/catalina.out.

**Comment by Treutler** [comment]
I do not see this warning. Please specify when this happens.

**Comment by tsufz** [comment]
localhost - - [12/Jul/2017:11:39:28 +0200] "POST /MassBank/cgi-bin/IndexCount.cgi HTTP/1.1" 200 1089 "-" "Jakarta Commons-HttpClient/3.1"

**Comment by Treutler** [comment]
I replaced the library '"Jakarta Commons-HttpClient/3.1"' in commit 3d996ee9aad8c16957f373e06ea792fe6a99861f. It should not be part of the current version of MassBank. Is your code up to date?

**Comment by tsufz** [comment]
No, maybe not. Should be the webapp dated from 06 July when I did build the new massbank.eu server. I will checkout with a test server.

**Comment by Treutler** [comment]
@tsufz can this issue be closed?
