### ISSUE TITLE
Pubchem resolver

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank-web#77]
I suggest to remove the leading CID: in the dispatcher because the ID can be used in the link. The CID: is removed in the pubchem resolver what needs time, checkout:

https://pubchem.ncbi.nlm.nih.gov/compound/CID:28516
https://pubchem.ncbi.nlm.nih.gov/compound/28516

@Treutler

**Comment by schymane** [comment]
We need the CID in the record (but not the link) to distinguish between SID and CID (on the MassBank end). This is written in the Record Format. You will have to make sure that the fix will be able to deal with records with either SIDs or CIDs and both – i.e. that we send SIDs to the substance database correctly …and CIDs to the compound
The example in the Record Index has both:
CH$LINK: PUBCHEM SID: 11916 CID:182232
https://pubchem.ncbi.nlm.nih.gov/substance/11916
https://pubchem.ncbi.nlm.nih.gov/compound/182232

**Comment by Treutler** [comment]
Fixed the pubchem links to differentiate between CID and SID in 0f33deeedb4443f3b804645730fb818b4dd484ed.
