### ISSUE TITLE
Peak annotation is missing in RecordDisplay.jsp

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank-web#78]
The peak annotation is not displayed:

PK$ANNOTATION: m/z tentative_formula mass error(ppm)
105.0698 C8H9+ -0.84
115.054  C9H7+ -1.971
133.0642 C9H9O1+ -4.49
151.0747 C9H11O2+ -4.37
161.0589 C10H9O2+ -5.00
179.0694 C10H11O3+ -4.86

You can download test records from AAFC or Eawag on http://massbank.eu/MassBank/SVN/OpenData/

**Comment by Treutler** [comment]
The PK$ANNOTATION fields are currently implemented in issue #9.

**Comment by tsufz** [comment]
I would appreciate if all existing fields are displayed by now. I have many errors on massbank.eu by servers searching for missing fields, eg. Warning: could not parse line in file 'UT001959.txt': 'SP$SCIENTIFIC_NAME: Mus musculus' Warning: could not parse line in file 'UT001959.txt': 'SP$NAME: mouse'

We cannot drop all services, the API is not working and the people should be able to use html grapping scripts to get the data.

**Comment by tsufz** [comment]
With RMassBank development, we know how annoying dropped services are, we had often problems with a down or changed CTS and so on. I would like to make it better, even if this is more work.

**Comment by Treutler** [comment]
The display of records is complete now by commit 19f8a15b59dfa3048f560831216306c4b76cade0.
