### ISSUE TITLE
Making NIST spectra format download available

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank-web#83]
We should make the download of NIST spectra available as soon as possible. This should include at least all free records (CC-BY SA or CC-BY marked), the NC should be separated and those from Waters DB should be excluded.

We should implement a script to generate the libraries in the backend regularly (once a week or so) such as the generation of the sitemaps and the statistics.

**Comment by meowcat** [comment]
WRT NIST representation of MassBank spectra: Is there already some agreement on a canonical way to represent complex attributes from MassBank spectra in MSP format?

See the discussion below on tags that are recognized by the NIST software. I proposed earlier to use Synon: $:99 to map additional tags to NIST. Also, talking to Steve Stein about implementation of this in NIST-MS search might be a good idea.

https://docs.google.com/document/d/13Fy1155GsH7L7lTqth2rzsuGU6YIz0YOlf4-SkGUtSc/edit#heading=h.7b33yzb6ohc1

**Comment by Treutler** [comment]
related to #103

**Comment by tsufz** [comment]
Fixed in MassBank/MassBank-data
