### ISSUE TITLE
Spurious "(3)" in record title on website

### ISSUE THREAD

**Issue by sneumann** [MassBank/MassBank-web#85]
Hi, when going to 
https://massbank.eu/MassBank/jsp/RecordDisplay.jsp?id=PB000166&dsn=IPB
The record title in blue is:
`Kaempferol; LC-ESI-QTOF; MS2; CE:40 eV; [M+H]+ (3)`
with that strange (3) in it. Further down in the record it is correctly:
`RECORD_TITLE: Kaempferol; LC-ESI-QTOF; MS2; CE:40 eV; [M+H]+`

This does not happen on the Japanese site:
http://www.massbank.jp/jsp/Dispatcher.jsp?type=disp&id=PB000166&site=9
`Kaempferol; LC-ESI-QTOF; MS2; CE:40 eV; [M+H]+`

**Comment by Treutler** [comment]
Fixed with commit f21363248613381f4f9ffb0d46f1d09d94ce0287
