### ISSUE TITLE
Embargo databases

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank-web#89]
I could be worth to think about something like embargo databases which are only viewable with tokens or passwords. The idea is that only reviewers or people from a project can access the DB.

**Comment by sneumann** [comment]
I would strongly try to avoid having to create a password system. That would imply to also protect the SVN, include/exclude from searches etc. 

A user who has records he or she wants as supplemental information and passed to the reviewers, but not (yet) in MassBank could instead use a record to HTML converter (i.e. exactly the HTML that would be visible in the Browser) and add that to the paper submission. 

Additional benefit: Users can preview their records before sending the recdata.zip to the MassBank admins. The SVG is already empedded and should display offline, but the SpecTackle doesn't work yet. You can 
```
wget --mirror --convert-links --adjust-extension --page-requisites --no-parent "https://msbi.ipb-halle.de/MassBank/jsp/RecordDisplay.jsp?id=PB006042&dsn=IPB"
```
and view the resulting file:///tmp/msbi.ipb-halle.de/MassBank/jsp/RecordDisplay.jsp%3Fid=PB006042&dsn=IPB.html but while the structure is there, the spectrum is not.

**Comment by sneumann** [comment]
The file below (it is HTML, but github insists I have to call it *.txt) was saved with the chrome extension 
https://chrome.google.com/webstore/detail/singlefile/mpiodijhokgodhhofbcjdecpffjipkle https://github.com/gildas-lormeau/SingleFile
[(+--) Salsolinol Mass Spectrum (2017-08-08 4-37-42 PM).htm.txt](https://github.com/MassBank/MassBank-web/files/1208452/--.Salsolinol.Mass.Spectrum.2017-08-08.4-37-42.PM.htm.txt)

**Comment by meowcat** [comment]
How hard would it be to run separate instances of MassBank for these cases? The HTML export solution would be a bit limited in terms of comfort and what you can do with it. For my own projects, we have an in-house MassBank instance running that worked well. For projects needing sharing across labs, one could think of a passworded (e.g. .htaccess) instance on an Amazon server or such? (Since IT departments typically make it complicated to open in-house servers to the public.)

**Comment by tsufz** [comment]
I will checkout. Should be no problem to run a secondary instance on massbank.eu with a virtual server under massbank.eu/project or so. Needs some adjustment of the installation files and a secondary MariaDB in order to avoid conflicts. I will check on my test server.

**Comment by Treutler** [comment]
Solution is to create private instances of MassBank. Hence, closing

**Comment by tsufz** [comment]
This is not solved yet. Just running a server clone is not that what DMZ admins like...

**Comment by sneumann** [comment]
Hi, I am afraid that a full-fledged *secure* user management plus record access management, secure SOAP/REST API implemented _inside_ MassBank is out of scope, hence we closed this. 

It should be possible to use some protection on the http(s) layer around a MassBank instance, and create one (set of) docker containers per such protected instance, all on one VM so just one FW ruleset would be required. User management would then be on the basis of some kind of .htaccess or whatever the http server redirecting to the instances supports. Yours, Steffen

**Comment by tsufz** [comment]
Yes, but why is this not discussed and the issue just closed?
