### ISSUE TITLE
Enhancement of DB model

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank-web#9]
MassBank should be searchable by SPLASH. We may also consider to update the DB model with some more indexes if we grab it anyway?

**Comment by m-arita** [comment]
Dear Tobias,

Regarding the SPLASH, my member Akie Mejia is considering using it in
MassBank spectra. My concern is, however, it is noise-sensitive. I
would like to "cleanse" experimental spectra by removing mass peaks to
which we cannot assign any molecular formula.  In addition, I also
want to remove peaks of very low intensities.  We will probably attach
SPLASH not only to original spectra (raw spectra registered to
MassBank) but to its cleansed spectra too in the coming version of
Massbank. The coming version here is the wiki-version now I am
preparing. This version will run in parallel with the current one.

Best wishes,

masanori arita


2016-01-25 16:26 GMT+09:00 Tobias Schulze <notifications@github.com>:
> MassBank should be searchable by SPLASH We may also consider to update the
> DB model with some more indexes if we grab it anyway?
>
> —
> Reply to this email directly or view it on GitHub.



-- 

Masanori Arita (arita@nig.ac.jp)
National Institute of Genetics
Yata 1111, Mishima City, 411-8540 Shizuoka, Japan
Tel:  +81-(0)-55-981-9449

**Comment by tsufz** [comment]
Dear Masanori,
Good to hear from you. We are aware of many noisy records in MassBank. 
The records processed with RMassBank are cleaned by default and only 
peaks with fragments assigning to the formula are added to the peak 
lists. Therefore those SPLASH should be rather clean.

We may find a solution to clean-up all mass spectra and distribute only 
clean spectra rather than different versions. However, we need some 
agreement with the data providers to confirm the reprocessing of their 
mass spectra.

I would not present different versions of one entry. In the 
wiki-version, we may include a tag that the records are reprocessed with 
our clean-up workflow.

Michele, Erik, do you think that we could use RMassBank to clean up and 
reprocess the old spectra?

Best wishes
Tobias

**Comment by meowcat** [comment]
Hi,

I don't see the issue with the SPLASH being applied to noisy spectra. From my understanding, the SPLASH is purely a hash identifier of the spectral data in a mass spectrum, and equally applicable to "clean" or "dirty" spectra. 

Wrt "cleaning up" old spectra, the idea has been brought up multiple times. One issue is that the RMassBank concept only works in a useful way with high-resolution spectra, and even 20ppm deviation might be a bit high. (I didn't test it specifically but it's my impression.) The other issue is that recalibration cannot be sensibly applied to such spectra if there is no information which were recorded "together" - so one advantage of RMB falls flat. But it could in principle be done (reading spectra and "purifying" them). I'm just not sure if we want to invest a lot of time into it.

**Comment by sneumann** [comment]
Hi, I fully agree with Michele, and SPLASHes should be calculated for spectra regardless of their "cleanness". An interesting question will be how different the histogram block 
will be between the current MassBank spectra and the cleaned ones in the Wiki. I also don't think 
that RMassBank can help a lot with cleaning for records without raw data. Yours, Steffen

**Comment by tsufz** [comment]
Hi,
I agree with Steffen's and Michele's proposals to wait until the cleaned 
spectra in the wiki are available. We should put efforts into the 
further development of the software and to convince the people and the 
vendors to use RMassBank and to provide build-in exporters, respectively.

I am sure that the latter one will appear quickly after the Agilent 
exporter will be available to the community. I will push then the Thermo 
people to consider that in Tracefinder development.

Best wishes, Tobias

**Comment by tsufz** [comment]
SPLASH resolving in Google is quite good now. I changed the dispatcher to link to Google and not to MoNA anymore.

**Comment by tsufz** [comment]
should also consider #11 and #21

**Comment by tsufz** [comment]
I suggest to build only one DB for all sub_DB. The names of contributors could be maintained in a contributor table. We may increase performance, but needs whole code review.

**Comment by Treutler** [comment]
I start to design a database schema covering as much entry data as possible. This will unify the fetching of data in MassBank by a database-manager in java and all relevant data will by searchable.

**Comment by tsufz** [comment]
Marc is also interested to join this action. He will contact @Treutler

**Comment by tsufz** [comment]
Please also consider to get rid of the accession code restrictions #11, the side ID and the dsn. A record should be easily searchable by it's accession. The side ID was probably used in those times of distributed server systems (each institute hosted their library on an own system and massbank.jp was only the search portal to federate). This is obsolete and should be eliminated.

**Comment by tsufz** [comment]
For the deployment of new record tags, I suggest to maintain a xml list (or something else) for easy implementation of new tags. The DB manager should read this table frequently and deploy new fields into the DB, update the search and display functions etc.

We may use a tags to control which tags are provided in display and search functions in order to avoid overload.

**Comment by Treutler** [comment]
This issue is addressed in branch [DatabaseExtension](https://github.com/MassBank/MassBank-web/tree/DatabaseExtension). There, the database schema is extended to cover the entire MassBank record format and to upload, query, and display all this data.

**Comment by naperone** [comment]
I continued extending the database schema with commit 842bd1b6265a7aeba4a3c9010a150f1680fbf2c5. It should include all tags specified in the MassBank Record Format 2.13 now. However, a lot of the changes are still commented out because of further changes that need to be made for the scripts not to fail with the insertion of the test data (these would be no longer syntactically correct).

In my opinion the db schema has several deficiencies right now:

1. It does not use primary keys or foreign keys and I don't see a reason why. Especially not using foreign keys leads to the necessity to manage all the id columns of the tables manually.
2. No behaviour for updates or deletes is specified (using ON UPDATE, ON DELETE)
3. The Record Format specifies a lot of restrictions on the domain of some tags, but these are not enforced within the db schema

I will start updating the schema to handle these deficiencies if there are no concerns with these changes.

**Comment by Treutler** [comment]
I fully appreciate the proposed changes 1, 2, and 3. 1 and 2 are crucial for a consistent schema and 3 is necessary to represent the record format in the database in an appropriate way. 
We will need a full code review after these changes, but this will lead to a unified and much more powerful handling of record data.
In addition, I could adapt the insertion of the initial GABA record entry afterwards.

**Comment by meowcat** [comment]
Hi,

may I repropose expanding the accession ID past 8 alphanumeric characters?
As discussed long ago in #11, the current CHAR(8) ID is very limiting, even more so if the rules of ABC12345 or AB123456 are followed. There is no necessity for such a narrow ID space, so I propose an extension to 16 or even more characters (why not 32 or 64?). 

Imagine e.g. a 16-character accession no. Of that one could dedicate 8 characters to "contributor IDs" and 8 characters to "spectrum IDs" (both alphanumeric, and for consistency with the old system uppercase-only). This gives near-limitless contributor IDs (could be administered with a small online DB or even just a Google Sheet) and near-complete freedom to the user of how to generate spectrum IDs.

**Comment by tsufz** [comment]
I agree to implement a full relational scheme. A full code review is also good in order of code deficiencies and vulnerabilities. The accession number is also an important issue. However, I like a MassBank based management, for example by a xml based on Github. I don't like external structures such as Google because the information must be parsed to the MassBank based DB. The xml could be managed by the MassBank admins as central contact points. Or we implement a general user based management of their records anyway (which creates vulnerabilities if not implemented properly...).

**Comment by naperone** [comment]
With commit 117bb39570cf2d9465fabdc3c422686df1c84fbb I addressed point 1 and 2 mentioned in my previous comment.

Regarding point number 3 I was planning to use regular expressions to define the domains of tags. However, I realised that this is not supported by mysql/mariadb and therefore not an option. For tags like accession numbers this means that within the db we can restrict only the datatype. Any further restriction needs to be implemented on the application layer. On the other hand tag domains like ch$link and ac$instrument_type could be restricted by predefining possible values in separate tables (which would work on all dbs). 

Extending the accession numbers as mention by @meowcat is no problem at all in my opinion it would only be necessary to agree on a mapping from the old domain to the new one.

**Comment by meowcat** [comment]
If the new accession number is not forced to be >8 characters on the DB/software side, one could do without mapping - just any 8-character AN is old format (and still a valid AN) and any longer AN is new format?

If there should be a mapping, the simplest option would just be to zerofill in front of the old AN, e.g. 00000000ABC12345. Is this a good idea? Someone with more knowledge than me about unique identifiers please comment...

Otherwise a possiblity would be to use "tagged" ANs, such as massbank8-ABC12345 and massbank16-ABCDABCDABCDABCD. Wouldn't work perfectly with the current "quick access via accession number" field but could be made to work...?

But I personally am in favor of permitting to continue use of the old IDs, since that leaves old records valid.

**Comment by tsufz** [comment]
I agree to allow the use of the old tags, but we should inject the new code as well. The old tags must be present in future anyway because they are the key to link from many publications and hence we can also allow to use them in future.

**Comment by meowcat** [comment]
If we want to have both in a record (i.e. inject old records with a new ID), it becomes a bit more complicated on the DB side, since the (old format) ID is currently also the link among all the tables, if I understand correctly... 

So the old ID would have to be copied to a purely "informational" field and only the new ID would be used internally for everything else

**Comment by Treutler** [comment]
Database schema was extended to represent the whole record. 
Regarding the extention of the accession ID see issue #11
