### ISSUE TITLE
Enhancement: Add http://bioschemas.org/ markup

### ISSUE THREAD

**Issue by sneumann** [MassBank/MassBank-web#94]
Hi, currently, the MassBank record HTML is a fairly plain view of the records. 
With http://bioschemas.org/ we can annotate what is a formula, what a SMILES etc. 
for better pickup by search engines.

**Comment by Treutler** [comment]
Possible type: Data Record
http://bioschemas.org/specifications/DataRecord/specification/

**Comment by Treutler** [comment]
implemented in f1e547f4a88c222742a05425ab2c1f78fbdfbfde
can be tested here: https://search.google.com/structured-data/testing-tool

**Comment by sneumann** [comment]
Please paste a URL here that can be used with the above `testing-tool`
once we have a public instance with an enhanced record visualisation. Yours, Steffen

**Comment by Treutler** [comment]
Missing / unimplemented tags are still welcome (:

**Comment by tsufz** [comment]
Hi guys, There is still some world outside of biology ;-).  Obviously, a more proper tagging of chemical content is also feasible: https://figshare.com/articles/Bringing_Chemical_Data_onto_the_Semantic_Web/3221377

**Comment by Treutler** [comment]
Thanks for the good hint, I will implement the applicable tags

**Comment by egonw** [comment]
Hi @Treutler, sorry I missed this issues. Last week at the BioHackathon meeting I contributed to the `MolecularEntity` and `ChemicalSubstance` profiles... I'll come up with a suggestion on how to use the former in MassBank.

**Comment by egonw** [comment]
Here's example `MolecularEntity` JSON-LD:

```json
{
	"@context": "http://schema.org",
	"@type": "MolecularEntity",
	"name": "3alpha-Hydroxy-5alpha-cholan-24-oic acid Methyl ester",
	"alternateName": [
		"Allolithocholic Acid Methyl ester"
	],
	"identifier": "NU000001",
	"url": "https://msbi.ipb-halle.de/MassBank/RecordDisplay.jsp?id=NU000001&dsn=Nihon_Univ",
	"molecularFormula": "C25H42O3",
	"monoisotopicMolecularWeight": 390.31340,
	"inChI": "InChI=1S/C25H42O3/c1-16(5-10-23(27)28-4)20-8-9-21-19-7-6-17-15-18(26)11-13-24(17,2)22(19)12-14-25(20,21)3/h16-22,26H,5-15H2,1-4H3/t16-,17+,18-,19+,20-,21+,22+,24+,25-/m1/s1",
	"smiles": ["C(C1(C)4)([H])(C(C)CCC(=O)OC)CCC1(C(C3([H])CC4)([H])CCC(C3(C)2)([H])CC(O)CC2)[H]"],
	"biologicalRole": [
		{
			"@type": "DefinedTerm",
			"@id": "http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C66892",
			"inDefinedTermSet":
				{
					"@type":"DefinedTermSet",
					"@id":"http://data.bioontology.org/ontologies/NCIT/submissions/69/download?apikey=8b5b7825-538d-40e0-9e9e-5ab9274a9aeb",
					"name": "National Cancer Institute Thesaurus"
				},
			"termCode": "C66892",
			"name": "natural product",
			"url": "http://bioportal.bioontology.org/ontologies/NCIT?p=classes&conceptid=http%3A%2F%2Fncicb.nci.nih.gov%2Fxml%2Fowl%2FEVS%2FThesaurus.owl%23C66892"
		}
  ]
}
```

**Comment by sneumann** [comment]
This is from a mail from Egon:
```
Hi Steffen,

in addition to the HMDB example I did last week (David, email is pending) [0], I just wrote up an BioSchemas MolecularEntity example for MassBank Europe:

https://github.com/elixir-europe/BioHackathon/blob/master/interoperability/Bioschemas/NU000001.json

This JSON-LD normally goes in the HTML head, i.e. as child under the <head> element, as explained in this page in the "Adding the script to your website" section: https://yoast.com/json-ld/

Egon

0.https://github.com/elixir-europe/BioHackathon/blob/master/interoperability/Bioschemas/HMDB0001188.json
```

**Comment by tsufz** [comment]
No complains anymore. The last missing object creator tag is an issue regarded to #194.
