### ISSUE TITLE
Record format: not available SMILES 

### ISSUE THREAD

**Issue by sneumann** [MassBank/MassBank-web#98]
Hi, I could not find a specification for "not available", e.g. for SMILES or Compound class etc.
What I found in current MassBank is:
```
grep -h SMILES */record/*.txt | uniq | sort | uniq -c | sort -n | tail
...
     18 CH$SMILES: NA
    402 CH$SMILES: N/A
```
Yours,
Steffen

**Comment by tsufz** [comment]
Okay will checkout and specify soon.

**Comment by tsufz** [comment]
Fixed
