### ISSUE TITLE
Validator should skip `N/A` SMILES

### ISSUE THREAD

**Issue by sneumann** [MassBank/MassBank-web#99]
The validator should just skip if SMILES are `N/A`.

```BS002004.txt
Exception in thread "main" java.lang.IllegalStateException: Can not parse SMILES string in "CH$SMILES" field.
...
Caused by: org.openscience.cdk.exception.InvalidSmilesException: could not parse 'not available', unexpected character:```

**Comment by sneumann** [comment]
So `N/A` should not fail the validation in https://github.com/MassBank/MassBank-web/blob/master/MassBank-Project/MassBank-lib/src/main/java/massbank/RecordParserDefinition.java#L399

**Comment by sneumann** [comment]
Agreed with Emma that (for now) we should accept `N/A`

**Comment by tsufz** [comment]
I agree. As long we cannot parse all to CDK depict, it makes no sense to make mandatory.

**Comment by schymane** [comment]
This is not just about CDK Depict: these extended SMILES are not yet a standard format and I thought we agreed they go in a different field for the special cases (where parts of the structure are undefined). I fear we will run into issues if we save non-standard SMILES into the CH$SMILES field - thus we will still need N/A or something ... an empty field is also non-ideal. We will also still have cases where we cannot even annotate with a partial smiles and we still need to deal with this.

-------------------------------------------
PI: EnvCheminf @ LCSB
emma.schymanski@uni.lu




On Wed, Dec 6, 2017 at 10:32 AM +0100, "Tobias Schulze" <notifications@github.com<mailto:notifications@github.com>> wrote:


I agree. As long we cannot parse all to CDK depict, it makes no sense to make mandatory.

**Comment by meier-rene** [comment]
I propose to make the CH$SMILES field optional in the massbank record format. This means it can be omitted if this information is not available. This is clearer compared to having invalid information in a field. Same applies to CH$IUPAC field which should contain the InChi.

**Comment by schymane** [comment]
I don't agree, we need this as a compulsory field...



On Wed, Dec 6, 2017 at 12:30 PM +0100, "René Meier" <notifications@github.com<mailto:notifications@github.com>> wrote:


I propose to make the CH$SMILES field optional in the massbank record format. This means it can be omitted if this information is not available. This is clearer compared to having invalid information in a field. Same applies to CH$IUPAC field which should contain the InChi.

**Comment by meier-rene** [comment]
`N/A` is implemented as possible value for CH$SMILES and CH$IUPAC. Its still marked with a TODO in source code and there need to be a solution for this in the future.
